cloudinit/net: handle identical ip routes
canonical/cloud-init pull request #1124
Opened 2021-11-30 16:02 UTC by esposem

## Proposed Commit Message

```
When configuring identical static and default routes to the same IP and
interface, cloudinit fails, with the stderr:
"RTNETLINK answers: File exists"

NetworkManager instead is able to handle such
setup essentially by using "ip route append" instead of
"ip route add".

Signed-off-by: Emanuele Giuseppe Esposito <eesposit@redhat.com>

RHBZ: #2003231
```

## Additional Context

## Test Steps

## Checklist:

 - [x ] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/contributing.html)
 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any documentation accordingly

2021-12-01 01:55 UTC, TheRealFalcon commented
@esposem , can you give me a little more context for this change? Why are you seeing the same route being added twice? How does using append fix it? Trying append twice still gives the same error for me:
```
$ ip -4 route append 192.168.1.1/32 dev eth0
$ ip -4 route append 192.168.1.1/32 dev eth0
RTNETLINK answers: File exists
```

This is in the Ephemeral IP network code, so if the route needed may already exist, does it make more sense to try the [connectivity url](https://github.com/canonical/cloud-init/blob/main/cloudinit/net/__init__.py#L1051) instead?

2021-12-03 02:32 UTC, zhaohuijuan commented
> @esposem , can you give me a little more context for this change? Why are you seeing the same route being added twice? How does using append fix it? Trying append twice still gives the same error for me:
> 
> ```
> $ ip -4 route append 192.168.1.1/32 dev eth0
> $ ip -4 route append 192.168.1.1/32 dev eth0
> RTNETLINK answers: File exists
> ```
> 
> This is in the Ephemeral IP network code, so if the route needed may already exist, does it make more sense to try the [connectivity url](https://github.com/canonical/cloud-init/blob/main/cloudinit/net/__init__.py#L1051) instead?

@TheRealFalcon , thanks for the review and questions. The context for this change comes from a specific configuration from customer.  

1. It fixs the scenario as below:
$ ip -4 route append 192.168.1.1/32 via 0.0.0.0 dev eth0
$ ip -4 route append 192.168.1.1/32 via 10.112.140.248 dev eth0
Not the same two routes as you mentioned below:
$ ip -4 route append 192.168.1.1/32 dev eth0
$ ip -4 route append 192.168.1.1/32 dev eth0

2. This bug comes from customer who set up routes in dhcp server side like this:
# cat /var/tmp/cloud-init/cloud-init-dhcp-f0rie5tm/dhcp.leases
lease {
  ...
  option classless-static-routes 31.169.254.169.254 0.0.0.0,31.169.254.169.254 10.112.143.127,22.10.112.140 0.0.0.0,0 10.112.140.1;
  ...
}
For the " option classless-static-routes 31.169.254.169.254 0.0.0.0,31.169.254.169.254 10.112.143.127,22.10.112.140 0.0.0.0,0 10.112.140.1;", cloud-init failed to configure it via 'ip route add'  due to there are two different routes for 169.254.169.254. But NetworkManager can handle such scenario successfully as it uses "ip route append". So cloud-init also changes to "ip route append" which can fix the issue.

3. For the scenario you mentioned:
$ ip -4 route append 192.168.1.1/32 dev eth0
$ ip -4 route append 192.168.1.1/32 dev eth0
I think it is another scenario, they are exactly the same route, although it reports error in log when config the second route, but the first route has been set up successfully, so anyway cloud-init can config the route successfully. And I think the error log also makes sense because it can reminder users that they config duplicate routes.

2021-12-03 16:04 UTC, TheRealFalcon approved these changes
Thanks, this makes sense now.

2021-12-03 16:06 UTC, TheRealFalcon requested changes
Sorry, shouldn't have hit that approve quite yet.

The change here looks good, but we still need an updated unit test as well. You should just be able to modify the currently failing one.

2021-12-06 09:14 UTC, esposem commented
Thank you @zhaohuijuan for the explanation, and @TheRealFalcon for the review! I updated the failing test case, and gave a better PR description according to Huijuan comments.

2021-12-06 17:16 UTC, TheRealFalcon approved these changes
LGTM now, thanks! I pushed a rebase of main due to a dependency issue. I can merge once CI completes successfully.

2021-12-06 17:34 UTC, merged