sources/azure: ensure retries on IMDS request failure
canonical/cloud-init pull request #1271
Opened 2022-02-16 04:41 UTC by cjp256

get_imds_data_with_api_fallback() will attempt one request with
IMDS_VER_WANT.  If the connection fails due to a timeout or other
connection issue, an empty dictionary will be returned without
attempting the requested number of retries.

Update get_imds_data_with_api_fallback() to invoke
get_metadata_from_imds() with the specified retries and infinite
parameters.  retry_on_url_exc will abort if an HTTP code other
than 404 is seen, so we will immediately see a 400 if it occurs
and fall back to the older API with the same retry parameters.

This also fixes an issue where IMDS_VER_WANT will never be attempted
if retries=0, such as when fetching network metadata with
infinite=True.

Signed-off-by: Chris Patterson <cpatterson@microsoft.com>

2022-02-16 14:29 UTC, anhvoms approved these changes

2022-02-16 15:03 UTC, anhvoms requested changes

2022-02-16 15:03 UTC, anhvoms commented on cloudinit/sources/DataSourceAzure.py
>          exc_cb=retry_on_url_exc,
retry_on_url_exc is only retrying on 404. We'll need to retry on 410 as well

2022-02-16 18:30 UTC, anhvoms approved these changes
Make sure you update the commit message (currently it mentions 404 only)

2022-02-16 18:34 UTC, cjp256 commented on cloudinit/url_helper.py
> +    msg, exc, *, retry_codes=(NOT_FOUND,), retry_instances=(requests.Timeout,)
Azure is the only user of this callback I think, but it seems reasonable that ConnectionError should also be included for retry.

2022-02-16 19:17 UTC, cjp256 commented
> Make sure you update the commit message (currently it mentions 404 only)

Squashed and updated PR.

2022-02-16 20:08 UTC, cjp256 commented
I'm happy with the changes now if you are @anhvoms

2022-02-16 20:25 UTC, anhvoms approved these changes

2022-02-18 00:12 UTC, holmanb commented
This looks good to me.

2022-02-18 00:12 UTC, holmanb approved these changes

2022-02-18 01:11 UTC, TheRealFalcon approved these changes
LGTM!

2022-02-18 01:15 UTC, merged