sources/azure: remove lease file parsing
canonical/cloud-init pull request #1302
Opened 2022-02-24 13:05 UTC by cjp256

With reporting ready now happening in local phase, we have access
to ephemeral DHCP lease options and no longer need to parse DHCP
lease files.

- Switch from tracking wireserver endpoint in its encoded form to the
  IP string, parsing it only when read from lease options.

- Drop fallback_lease_file and dhcp_options parameters in favor of
  processed endpoint string.

- Add some minor type information for mypy.

Signed-off-by: Chris Patterson <cpatterson@microsoft.com>

2022-03-04 17:26 UTC, anhvoms approved these changes
LGTM!

2022-03-07 19:32 UTC, TheRealFalcon approved these changes
LGTM! I'm going to close/re-open to re-trigger CI

2022-03-07 20:24 UTC, TheRealFalcon requested changes
Looks like there's still some broken tests.

2022-03-08 12:19 UTC, cjp256 commented
Fixed tests & rebased

2022-03-08 14:25 UTC, holmanb commented
> There seems to be an unrelated failure in the tests:

This is the second time I've seen that failure in the last this week. I think this is a flaky test that should be removed from CI. This depends on multiple keyservers so remote failure is likely cause, not your changes. A no-op push should get tests passing. I am proposing a separate PR to remove that test from CI runs.

2022-03-08 14:27 UTC, cjp256 commented
It failed twice this morning so I had just pushed -vv to the tests for better visibility.

2022-03-08 14:32 UTC, TheRealFalcon commented
We're putting up a PR to (re)move the test. It's failing because ssh-import-id is failing, which would be due to the Launchpad or Github service being down and unrelated to cloud-init.

2022-03-08 14:58 UTC, TheRealFalcon commented
I see that it failed again which indicates a different problem, but it is still a problem with ssh-import-id and not cloud-init, so I still moved the test out of CI. If you rebase, we should be able to pass now.

2022-03-08 15:01 UTC, cjp256 commented
Done

2022-03-08 16:01 UTC, TheRealFalcon approved these changes
Thanks!

2022-03-08 16:01 UTC, merged