Support EC2 tags in instance metadata
canonical/cloud-init pull request #1309
Opened 2022-02-27 01:24 UTC by edudobay

## Proposed Commit Message

```
Support EC2 tags in instance metadata

Add support for newer EC2 metadata versions (up to 2021-03-23), so that
tags can be retrieved from the `ds.meta_data.tags` field, as well as
with any new fields that might have been added since the 2018-09-24
version.
```

## Additional Context
I'm not sure about:
* whether I should have used the latest available metadata version as of today (`2021-07-15`, that is one release after the one I wrote). I ended up using the minimum version that supported tags.
    * Maybe the commit message should be modified to reflect other changes (beyond `tags`) that come with that upgrade?
* whether I chose a good testing strategy. My tests would actually pass without the changes I did, so I would appreciate some guidance on how to test something more useful.

## Test Steps

* Enable tags on metadata for the EC2 instance. On the CLI: `aws ec2 modify-instance-metadata-options --instance-id i-008d165d6a0f08d9d --instance-metadata-tags enabled`
* Install the updated `cloud-init` on the instance
* Reboot it and verify that tags are available: `cloud-init query ds.meta_data.tags`

## Checklist:

 - [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/contributing.html)
 - [x] I have updated or added any unit tests accordingly
 - [x] I have updated or added any documentation accordingly

2022-03-04 23:43 UTC, blackboxsw requested changes
Thanks so much for the PR @edudobay. I can confirm you have signed the cloud-init Contributor agreement and that your PR follows our process. You are correct in folowing our general policy of only bumping the metadata version to the minimal API version required to obtain the feature we care to support as some clouds that present an Ec2-like API may not adopt/provide official API versions which match strict Ec2. We don't want to inadvertently add all official API  versions as that could introduce a significant delay attempting to curl each and every API version on other Ec2-like clouds.


Thank you again for the doc update, given that we now have another API version we support in cloud-init for EC2-like clouds I'd like us to create a table of versions and features to call out.


Here's a suggested patch to see what you think. If acceptable or if you have changes there let's go for it and we can get this merged.

```diff
diff --git a/doc/rtd/topics/datasources/ec2.rst b/doc/rtd/topics/datasources/ec2.rst
index ada0ac7ca..e93c7ce0f 100644
--- a/doc/rtd/topics/datasources/ec2.rst
+++ b/doc/rtd/topics/datasources/ec2.rst
@@ -38,15 +38,26 @@ Userdata is accessible via the following URL:
     GET http://169.254.169.254/2009-04-04/user-data
     1234,fred,reboot,true | 4512,jimbo, | 173,,,
 
-Note that there are multiple versions of this data provided, cloud-init
-by default uses **2009-04-04** but newer versions can be supported with
-relative ease (newer versions have more data exposed, while maintaining
-backward compatibility with the previous versions).
-Version **2016-09-02** is required for secondary IP address support.
+Note that there are multiple EC2 Metadata versions of this data provided
+to instances. cloud-init will attempt to use the most recent API version it
+supports in order to get latest API features and instance-data. If a given
+API version is not exposed the instance, those API features will be
+unavailable to the instance.
+
+
++----------------+----------------------------------------------------------+
++ EC2 version    | supported instance-data/feature                          |
++================+==========================================================+
++ **2021-03-23** | Required for Instance tag support. This feature must be  |
+|                | enabled individually on each instance.  See the          |
+|                | `EC2 tags user guide`_.                                  |
++----------------+----------------------------------------------------------+
+| **2016-09-02** | Required for secondary IP address support.               |
++----------------+----------------------------------------------------------+
+| **2009-04-04** | Minimum supports EC2 API version for meta-data and       |
+|                | user-data.                                               |
++----------------+----------------------------------------------------------+
 
-For instance tags support, version **2021-03-23** is required, and the feature
-must be enabled individually on each instance — more information on the `EC2
-user guide <https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#work-with-tags-in-IMDS>`_.
 
 To see which versions are supported from your cloud provider use the following
 URL:
@@ -75,7 +86,7 @@ configuration (in `/etc/cloud/cloud.cfg` or `/etc/cloud/cloud.cfg.d/`).
 
 The settings that may be configured are:
 
- * **metadata_urls**: This list of urls will be searched for an Ec2
+ * **metadata_urls**: This list of urls will be searched for an EC2
    metadata service. The first entry that successfully returns a 200 response
    for <url>/<version>/meta-data/instance-id will be selected.
    (default: ['http://169.254.169.254', 'http://instance-data:8773']).
@@ -125,4 +136,5 @@ Notes
    For example: the primary NIC will have a DHCP route-metric of 100,
    the next NIC will be 200.
 
+.. _EC2 tags user guide: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#work-with-tags-in-IMDS
 .. vi: textwidth=79
```

2022-03-04 23:43 UTC, blackboxsw commented on cloudinit/sources/DataSourceEc2.py
> +    extended_metadata_versions = ["2021-03-23", "2018-09-24", "2016-09-02"]
I can confirm the "new" metadata cloud-init sees will provide instances with the following new instance-data keys
instance-life-cycle, tags, availability-zone-id and region which will not break cloud-init expectations for meta-data format.

```diff
--- orig	2022-03-04 22:29:44.311914976 +0000
+++ new	2022-03-04 22:29:18.455546794 +0000
@@ -13,7 +13,7 @@
  "distro_version": "18.04",
  "ds": {
   "_doc": "EXPERIMENTAL: The structure and format of content scoped under the 'ds' key may change in subsequent releases of cloud-init.",
-  "_metadata_api_version": "2018-09-24",
+  "_metadata_api_version": "2021-03-23",
   "dynamic": {
    "instance-identity": {
     "document": {
@@ -111,6 +111,7 @@
    },
    "instance-action": "none",
    "instance-id": "i-0d066a4a72aa5436b",
+   "instance-life-cycle": "on-demand",
    "instance-type": "t2.micro",
    "local-hostname": "ip-172-31-49-237.ec2.internal",
    "local-ipv4": "172.31.49.237",
@@ -145,7 +146,9 @@
     }
    },
    "placement": {
-    "availability-zone": "us-east-1e"
+    "availability-zone": "us-east-1e",
+    "availability-zone-id": "use1-az3",
+    "region": "us-east-1"
    },
    "product-codes": "ex9l8qw4x21426rsfg7am8gym",
    "profile": "default-hvm",
@@ -161,6 +164,12 @@
    "services": {
     "domain": "amazonaws.com",
     "partition": "aws"
+   },
+   "tags": {
+    "instance": {
+     "tag-1": "",
+     "tag2": "asdf"
+    }
    }
   }
  },
```

2022-03-05 03:28 UTC, blackboxsw commented on tests/unittests/sources/test_ec2.py
> +    "tags": {"instance": {"Environment": "production", "Application": "test"}},
Could you also please add a tag without value example here too, just so we have a reference of what's expected on Empty vals.
```suggestion
    "tags": {"instance": {"Environment": "production", "Application": "test", "TagWithoutValue": ""}},
```

2022-03-16 02:22 UTC, edudobay commented on cloudinit/sources/DataSourceEc2.py
> +    extended_metadata_versions = ["2021-03-23", "2018-09-24", "2016-09-02"]
Hi @blackboxsw and thanks for the feedback! Sorry I've taken a while to come back to this. Regarding these other new fields, is there anything you'd like me to adjust in this PR? I'll make the remaining changes in the next few days.

2022-03-29 18:34 UTC, blackboxsw commented on cloudinit/sources/DataSourceEc2.py
> +    extended_metadata_versions = ["2021-03-23", "2018-09-24", "2016-09-02"]
@edudobay sorry I didn't see this response, I think the addition of docs and and the [minor unittest](https://github.com/canonical/cloud-init/pull/1309#discussion_r820029886) tweak should suffice and we can merge this.

2022-04-04 01:41 UTC, edudobay commented on cloudinit/sources/DataSourceEc2.py
> +    extended_metadata_versions = ["2021-03-23", "2018-09-24", "2016-09-02"]
Hello @blackboxsw, I've just made the changes you suggested.

2022-04-06 04:26 UTC, blackboxsw approved these changes
Thank you for these updates @edudobay I confirm that the Canonical contributor license agreement (CLA) is signed and this changeset adheres to our contributor guidelines. Thanks again for the contribution here and making cloud-init better  on Ec2!

2022-04-06 04:28 UTC, merged