prevent cloudinit/config/cc_ssh_authkey_fingerprints.py from creating home when "no_create_home: true", or "system: true"
canonical/cloud-init pull request #1343
Opened 2022-03-19 07:43 UTC by jf

## Proposed Commit Message

prevent cc_ssh_authkey_fingerprints.py from inadvertently creating a home when "no_create_home: true", or "system: true"

```
summary: stop cc_ssh_authkey_fingerprints from ALWAYS creating home

cloudinit/config/cc_ssh_authkey_fingerprints.py unintentionally ends
up creating a home directory for a user, even when `no_create_home:
true` or `system: true`. This prevents it.

`cc_ssh_authkey_fingerprints.py` calls `ssh_util.extract_authorized_keys`,
which ends up calling `check_create_path`, which creates the as yet
non-existent home while looking for a `authorized_keys` file to parse.
`cc_ssh_authkey_fingerprints.py` looks like the best place to stop this.

NOTE that I do not handle the situation where (`no_create_home: true`
or `system: true`) *and* yet `ssh_authorized_keys` is provided. In
this case, by virtue of the code `no_create_home: true` / `system:
true` takes precedence
```

## Additional Context

## Test Steps

sample user data:
```
#cloud-config

system_info:
  default_user:
    name: jf

users:
  - default

  - name: nch
    no_create_home: true

  - name: system
    system: true
```

## Checklist:

 - [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/contributing.html)
 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any documentation accordingly

2022-03-24 20:19 UTC, TheRealFalcon requested changes
Thanks @jf , this looks good to me.

I put together a quick integration test. Would you mind adding it to the end of tests/integration_tests/modules/test_ssh_auth_key_fingerprints.py?
```python
@pytest.mark.user_data(
    """\
#cloud-config
users:
 - default
 - name: nch
   no_create_home: true
 - name: system
   system: true
"""
)
def test_no_home_directory_created(client: IntegrationInstance):
    """Ensure cc_ssh_authkey_fingerprints doesn't create user directories"""
    home_output = client.execute("ls /home")
    assert "nch" not in home_output
    assert "system" not in home_output

    passwd = client.execute("cat /etc/passwd")
    assert "nch:" in passwd
    assert "system:" in passwd
```

2022-03-25 00:50 UTC, jf commented
thank you, @TheRealFalcon . This is done now

2022-03-25 02:43 UTC, TheRealFalcon approved these changes
Thanks!

2022-03-25 13:43 UTC, TheRealFalcon commented
Sorry, forgot to specify the import. Thanks for fixing that.

2022-03-25 13:44 UTC, merged

2022-03-25 15:03 UTC, jf commented
> Sorry, forgot to specify the import. Thanks for fixing that.

sure. Thanks for the testing code! I didn't really know how to start on that...