schema: add json defs for modules e-install
canonical/cloud-init pull request #1366
Opened 2022-04-03 03:52 UTC by TheRealFalcon

## Proposed Commit Message

```
schema: add json defs for modules e-install

* cc_emit_upstart (removal)
* cc_fan
* cc_final_message
* cc_foo
* cc_growpart
* cc_grub_dpkg
* cc_install_hotplug
```

## Additional Context
Removed 'cc_emit_upstart' entirely. According to https://upstart.ubuntu.com/ , the only place we'll see upstart anymore is trusty and RHEL 6, neither of which will ever see a new upstream change

2022-04-03 03:53 UTC, TheRealFalcon commented on cloudinit/config/cc_grub_dpkg.py
> +    idevs_empty = util.get_cfg_option_bool(
Small change here to accommodate deprecating the string option here. Also had to modify the test for this module.

2022-04-05 02:47 UTC, blackboxsw requested changes
Looks pretty good. Inline comments throughout. I don't feel too strongly about the cc_growpart logic, but I think we we are truly going to deprecate some of these values or types, we should per logging deprecation warnings about them in this release.

2022-04-05 16:39 UTC, TheRealFalcon commented on cloudinit/config/cloud-init-schema.json
> +                {"enum": ["auto", "growpart", "gpart", "off"]}
Nice! Didn't know it was possible to have enum with multiple types inside

2022-04-05 16:44 UTC, TheRealFalcon commented
Pushed next set from comments.

> I think we we are truly going to deprecate some of these values or types, we should per logging deprecation warnings about them in this release

I think I added warnings for everything here

2022-04-05 16:46 UTC, TheRealFalcon commented on cloudinit/config/cc_fan.py
>      - write ``config_path`` with the contents of the ``config`` key
Done

2022-04-05 16:46 UTC, TheRealFalcon commented on cloudinit/config/cc_final_message.py
>  specified as a jinja template with the following variables set:
Done

2022-04-05 17:51 UTC, blackboxsw approved these changes
Well done, thanks for the updates here.

2022-04-05 17:52 UTC, merged