Add python3-debconf
canonical/cloud-init pull request #1507
Opened 2022-06-10 06:59 UTC by aciba90

Do not squash
SC-1102

2022-06-16 19:37 UTC, blackboxsw requested changes
ditto on the other packaging PRs. Thanks for working this @aciba90 we'll land tomorrow with the minor fixes.

2022-06-16 19:37 UTC, blackboxsw commented on debian/changelog
> +cloud-init (22.2-0ubuntu1~18.04.1) UNRELEASED; urgency=medium
```suggestion
cloud-init (22.2-0ubuntu1~18.04.2) UNRELEASED; urgency=medium
```

2022-06-16 19:37 UTC, blackboxsw commented on debian/control
> +         python3-debconf,
We also need this in Build-Depends too. See https://github.com/canonical/cloud-init/pull/1511 for context.

2022-06-16 19:37 UTC, blackboxsw commented on debian/changelog
> +    - add Depends: python3-debconf
```suggestion
  * d/control: add Depends: python3-debconf
```

2022-06-20 09:33 UTC, aciba90 commented
Thanks for the review @blackboxsw. Ready to be reviewed.

2022-06-20 15:37 UTC, merged