Ubuntu/impish: Add Depends: python3-debconf
canonical/cloud-init pull request #1509
Opened 2022-06-10 07:19 UTC by aciba90

Depends: python3-debconf added in https://github.com/canonical/cloud-init/pull/1506 and https://github.com/canonical/cloud-init/pull/1472

SC-1102

(Do not squash)

2022-06-16 19:35 UTC, blackboxsw requested changes
Thanks @aciba90  for the pkging branches. Same comments as other PRs.

2022-06-16 19:35 UTC, blackboxsw commented on debian/changelog
> +cloud-init (22.2-0ubuntu1~21.10.1) UNRELEASED; urgency=medium
```suggestion
cloud-init (22.2-0ubuntu1~21.10.2) UNRELEASED; urgency=medium
```

2022-06-16 19:35 UTC, blackboxsw commented on debian/control
> +         python3-debconf,
We also need this in Build-Depends too. See https://github.com/canonical/cloud-init/pull/1511 for context.

2022-06-20 09:37 UTC, aciba90 commented
Thanks for the review @blackboxsw. I have applied the requested changes. Ready to be reviewed.

2022-06-20 15:38 UTC, merged