Ubuntu/jammy: Add Depends: python3-debconf
canonical/cloud-init pull request #1510
Opened 2022-06-10 07:27 UTC by aciba90

Depends: python3-debconf added in https://github.com/canonical/cloud-init/pull/1506 and https://github.com/canonical/cloud-init/pull/1472

SC-1102

(Do not squash)

2022-06-16 19:33 UTC, blackboxsw requested changes

2022-06-16 19:33 UTC, blackboxsw commented on debian/changelog
> +cloud-init (22.2-0ubuntu1~22.04.1) UNRELEASED; urgency=medium
Note we can't reuse an already released version 22.2-0ubuntu1~22.04.1 in debian/changelog, so we'd want this to be
```suggestion
cloud-init (22.2-0ubuntu1~22.04.2) UNRELEASED; urgency=medium
```

2022-06-16 19:33 UTC, blackboxsw commented on debian/changelog
> +  * d/control:
Let's make this just one line

2022-06-16 19:33 UTC, blackboxsw commented on debian/control
> +         python3-debconf,
We also need this in Build-Depends too. See https://github.com/canonical/cloud-init/pull/1511 for context.

2022-06-20 09:37 UTC, aciba90 commented
Thanks for the review @blackboxsw. I have applied the requested changes. Ready to be reviewed.

2022-06-20 15:35 UTC, blackboxsw approved these changes

2022-06-20 15:38 UTC, merged