d/control: add python3-debconf to Build-Depends
canonical/cloud-init pull request #1535
Opened 2022-06-20 09:32 UTC by aciba90

## Proposed Commit Message

```
d/control: add python3-debconf to Build-Depends
```

## Additional Context

Added to be able to run python3-debconf unittests.

SC-1102
https://github.com/canonical/cloud-init/pull/1511/files#r899456743

## Test Steps

`make deb`

## Checklist:

 - [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/contributing.html)
 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any documentation accordingly

2022-06-20 16:00 UTC, aciba90 commented
Reopening to trigger CI.

2022-06-20 19:50 UTC, aciba90 commented
@blackboxsw I created this PR to align `main` with the contents of our `ubuntu/<release>` branches.

2022-06-21 22:03 UTC, blackboxsw requested changes
So, the reason that we don't have any explicit build dependencies listed is due to our magic package template builder scripts.

`./tools/read-dependencies` gets distro-specific pkg dependencies when building a local  deb or RPM package based dependencies listed in `requirements.txt` and `test-requirements.txt` and supplemented or renamed to python3-<pkg_name> base on the distro keys or renames listed in `packages/pkg-deps.json`.  Then `package/bddeb` will replace ${build_depends} with that full lest of test and runtime dependencies when rendering the debian/control.in template.

This is one-off local developer tool that relies on copying out the `packages/debian` directory copied into a tmpdir in order to build the local test package.

Long-term I think we probably want to simplify some of this logic to avoid duplicating efforts across our ubuntu/*/debian/ packaging branches. But for this PR let's just ensure we ttweak the pkgs-debs.json to add python3-debconf.
```diff
diff --git a/packages/pkg-deps.json b/packages/pkg-deps.json
index 36e6b38f7..8ba27e855 100644
--- a/packages/pkg-deps.json
+++ b/packages/pkg-deps.json
@@ -3,7 +3,8 @@
       "build-requires" : [
          "debhelper",
          "dh-python",
-         "dh-systemd"
+         "dh-systemd",
+         "python3-debconf"
       ],
       "renames" : {
          "pyyaml" : "python3-yaml",
```
I think we want to drop python3-debconf from an explicit mention in the control.in for the moment and we can discuss retiring these scripts and JSON metadata separately.

2022-06-22 14:05 UTC, aciba90 commented
Thanks, @blackboxsw,  for the complete explanation. I saw superficially `package/bddeb`, but I did not go deeper and I should have looked. This is ready to review.

2022-06-22 14:25 UTC, blackboxsw approved these changes

2022-06-22 14:26 UTC, merged