Fix comment typo regarding use of `packages:` and relationship to `package_update:`
canonical/cloud-init pull request #1582
Opened 2022-07-12 07:04 UTC by magnetikonline

## Proposed Commit Message

Fix comment typo regarding use of `packages:` and relationship to `package_update:`

```
Found a small typo in the online documentation.
```

## Additional Context

N/A

## Test Steps

N/A

## Checklist:

 - [ ] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/contributing.html)
 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any documentation accordingly

2022-07-12 07:35 UTC, aciba90 requested changes
Thanks, @magnetikonline, for making `cloud-init` better.

Could you please sign the CLA and add yourself to [tools/.github-cla-signers](https://github.com/canonical/cloud-init/blob/main/tools/.github-cla-signers) ?

More info: https://cloudinit.readthedocs.io/en/latest/topics/contributing.html#summary

2022-07-13 00:46 UTC, magnetikonline commented on tools/.github-cla-signers
> +magnetikonline
Username added @aciba90 👍

2022-07-13 00:46 UTC, magnetikonline commented
> Could you please sign the CLA and add yourself to [tools/.github-cla-signers](https://github.com/canonical/cloud-init/blob/main/tools/.github-cla-signers) ?

Thanks @aciba90 - all done 👍

2022-07-13 09:09 UTC, aciba90 approved these changes
LGTM!

2022-07-13 10:55 UTC, magnetikonline commented
Thanks @aciba90

2022-07-14 01:47 UTC, TheRealFalcon approved these changes
Thanks for the contribution, @magnetikonline !

2022-07-14 01:48 UTC, merged

2022-07-14 01:50 UTC, magnetikonline commented
Not a problem @TheRealFalcon - just been getting into another great Canonical project in Multipass - and started authoring `cloud-init.yml` files. 👍