Add btrfs and lvm support to lxd storage options (SC-1026)
canonical/cloud-init pull request #1585
Opened 2022-07-12 17:50 UTC by holmanb

```
Add btrfs and lvm support to lxd storage options
```

2022-07-14 02:09 UTC, TheRealFalcon commented
Do you have plans to add ceph too? IIRC, ceph was going to be one of LXDs main storage backends. It doesn't have to be this PR, but I think it should be part of the overall effort here.

2022-07-14 02:58 UTC, blackboxsw commented
> Do you have plans to add ceph too? IIRC, ceph was going to be one of LXDs main storage backends. It doesn't have to be this PR, but I think it should be part of the overall effort here.

I think we had a planing discussion with @stgraber about ceph vs btfs and lvm and I thought I recall ceph being deprioritized as part of that discussion.

2022-07-14 03:05 UTC, blackboxsw reviewed
Would we be able to integration tests add storage_backends btfs and lvm?

2022-07-14 03:12 UTC, blackboxsw requested changes
Thanks @holmanb. I think we need a bit more test coverage. at least unittests covering the logic under `get_required_packages` and the mocked calls to `cloud.distro.install_packages(packages)`

Ideally we'd get an integration test or two around for this, but maybe that needs a separate PR?

2022-07-14 03:12 UTC, blackboxsw commented on tests/unittests/config/test_cc_lxd.py
> +                self.assertTrue(mock_subp.which.called)
This assertion should be more specific to the backend or maybe more generally we should have a class TestGetRequiredPackages which asserts the package string returned from get_required_packages and the specific "which" calls when the package is "present" vs absent.

2022-07-14 03:53 UTC, stgraber commented
> I think we had a planing discussion with @stgraber about ceph vs btfs and lvm and I thought I recall ceph being deprioritized as part of that discussion.

Yeah, basically the conclusion was that dir, btrfs and zfs are pretty common on standalone servers and may make sense to directly support. For other setups, you're likely better off just using a full LXD init preseed.

That's particularly true of Ceph which isn't exactly something trivial to setup on a single server. You're usually dealing with a cluster of server, need keyrings to be issued and deployed, ... Not something that's particularly likely to be done entirely through cloud-init.

2022-07-14 18:35 UTC, holmanb commented
> at least unittests covering the logic under get_required_packages and the mocked calls to cloud.distro.install_packages(packages)

After implementing tests for get_required_packages and the mocked calls to `cloud.distro.install_packages()`, I realized that implementing the `install_packages()` tests renders `get_required_packages()` as an implementation detail that is already covered. I'll leave it up to a round 2 review to decide whether or not to drop `get_required_packages()` tests.

2022-07-14 18:44 UTC, holmanb commented
Oh that's interesting. `black` is complaining about a file I didn't touch (`cloudinit/sources/helpers/azure.py`), despite `black` passing locally. I'll rebase on main to force a re-run.

2022-07-14 22:54 UTC, blackboxsw commented
> Oh that's interesting. `black` is complaining about a file I didn't touch (`cloudinit/sources/helpers/azure.py`), despite `black` passing locally. I'll rebase on main to force a re-run.

I saw this on my local PR too. Somehow we managed to merge a PR that should have failed the black check in github actions. not sure how. I had opted to fix format this locally in my PR. The alternative I was looking at was whether tox could support a subshell call like the following for our black formatting:

`tox/black/bin/python3 -m black  $(git diff --diff-filter=d --name-only upstream/main | grep py$)`

2022-07-15 19:39 UTC, blackboxsw approved these changes
Looks good @holmanb,

Let's just tweak our existing integration test from the default `storage_backend: dir` to storage_backend: btrfs` as it'll also let us assert that the btrfs utils are installed

```diff
diff --git a/tests/integration_tests/modules/test_lxd_bridge.py b/tests/integration_tests/modules/test_lxd_bridge.py
index 3292a833d..735b9cc9a 100644
--- a/tests/integration_tests/modules/test_lxd_bridge.py
+++ b/tests/integration_tests/modules/test_lxd_bridge.py
@@ -12,7 +12,7 @@ USER_DATA = """\
 #cloud-config
bootcmd:
  
 lxd:
   init:
-    storage_backend: dir
+    storage_backend: btrfs
   bridge:
     mode: new
     name: lxdbr0
```

2022-07-15 21:55 UTC, holmanb commented
> We could optionally apt remove btrfs-progs in a bootcmd if we wanted to assert it was installed in the process

I took your suggestion on this, thanks!

@blackboxsw If the extra line looks good to you I think I'm ready to merge this.

2022-07-18 14:29 UTC, merged