freebsd: Don't assume that root user is in root group
canonical/cloud-init pull request #1587
Opened 2022-07-12 22:37 UTC by holmanb

```
Don't assume root user is in root group

freebsd's root user has group "wheel"

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=265177
```

2022-07-12 23:15 UTC, holmanb commented
Ah, it looks like I have freebsd source local from the last time I looked at a freebsd bug. I see:
```
arc~/workspace/freebsd-src(main|✔) grep root etc/group
wheel:*:0:root
operator:*:5:root
```

2022-07-12 23:16 UTC, holmanb commented
@igalic do you have time for a quick review? I'd like a review from a freebsd user or developer.

2022-07-13 09:25 UTC, igalic requested changes
minor change for a big impact ;)

2022-07-13 09:25 UTC, igalic commented on cloudinit/distros/freebsd.py
> +    default_owner = "root:wheel"
this is the case for all BSDs, so this can go into bsd.py

2022-07-13 14:03 UTC, holmanb commented
@igalic Thanks for the review! It should be good now I think.

2022-07-14 02:45 UTC, TheRealFalcon approved these changes
LGTM, though I won't merge right now to see if we have anymore comments.

2022-07-14 16:03 UTC, holmanb commented
Thanks for the reviews @igalic and @TheRealFalcon! Merging now.

2022-07-14 16:05 UTC, merged