Measure Integration Tests
canonical/cloud-init pull request #1638
Opened 2022-08-05 20:07 UTC by holmanb

```
test: Collect integration test time by default
```

2022-08-09 15:25 UTC, holmanb commented
This stems from discussion last week about increasing total runtime of CI integration tests. 
```
============================= slowest 10 durations =============================

136.23s setup    tests/integration_tests/modules/test_combined.py::TestCombined::test_final_message

134.97s setup    tests/integration_tests/test_shell_script_by_frequency.py::test_per_freq

118.48s setup    tests/integration_tests/modules/test_set_hostname.py::TestHostname::test_hostname_and_fqdn

116.99s setup    tests/integration_tests/modules/test_write_files.py::TestWriteFiles::test_write_files[file /root/file_b64-ASCII text]

116.65s setup    tests/integration_tests/modules/test_set_hostname.py::TestHostname::test_prefer_short_hostname

116.54s setup    tests/integration_tests/modules/test_set_password.py::TestPasswordUsersList::test_no_duplicate_users_in_shadow

115.92s setup    tests/integration_tests/modules/test_set_hostname.py::TestHostname::test_prefer_fqdn

115.47s setup    tests/integration_tests/modules/test_ssh_auth_key_fingerprints.py::TestSshAuthkeyFingerprints::test_ssh_authkey_fingerprints_disable

115.39s setup    tests/integration_tests/modules/test_set_hostname.py::TestHostname::test_hostname

115.37s setup    tests/integration_tests/modules/test_ssh_keys_provided.py::TestSshKeysProvided::test_ssh_provided_keys[/etc/ssh/ssh_host_dsa_key.pub-AAAAB3NzaC1kc3MAAACBAPkWy1zbchVIN7qTgM0/yyY8q4RZS8cNM4ZpeuE5UB/Nnr6OSU/nmbO8LuM]

=== 114 passed, 3 skipped, 130 deselected, 16 warnings in 1650.68s (0:27:30) ===
```

2022-08-10 19:58 UTC, TheRealFalcon approved these changes
Is the coverage just for your own curiosity? The goal for integration tests will never be 100%, or even close.

2022-08-10 20:33 UTC, holmanb commented
> Is the coverage just for your own curiosity? The goal for integration tests will never be 100%, or even close.

Oops, no coverage doesn't make sense. That's just some sloppy copy-paste, I'll remove that.

2022-08-12 11:04 UTC, aciba90 requested changes
Minor comment. Otherwise, LGTM, thanks!

2022-08-12 11:04 UTC, aciba90 commented on integration-requirements.txt
> +pytest-cov
As coverage is not needed, I think it's safe to remove this.

```suggestion
```

2022-08-12 15:14 UTC, merged