config: Support APT automated mirror selection
canonical/cloud-init pull request #1670
Opened 2022-08-18 10:30 UTC by waldiTM

## Proposed Commit Message
```
config: Support APT automated mirror selection

The automated mirror selection supported by APT for some time now allows
to separate most info in sources.list from the mirror URL itself.  A new
config option asks cloud-init to write one mirror file for primary and
one for security mirror.

To write just the mirrors lists, cloud-init does not longer need to know 
about the dists to enable/disable and what the release is to begin with.
On Debian those information is not readily available in all cases.
```

## Additional Context
This will be used in addition https://salsa.debian.org/cloud-team/debian-cloud-images/-/merge_requests/279 to allow mirror selection by cloud-init

## Test Steps

## Checklist:

 - [ ] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/contributing.html)
 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any documentation accordingly

2022-08-23 15:52 UTC, TheRealFalcon commented
@waldiTM , thanks for the PR. Can you provide some examples of how you think this would be used and how the functionality works? I'm having a hard time finding any kind of documentation for this feature in apt.

Additionally, before we can accept your change, you need to sign [the CLA](https://ubuntu.com/legal/contributors/agreement) and add your Github username (alphabetically) to [the cla signers file](https://github.com/canonical/cloud-init/blob/master/tools/.github-cla-signers) . The full details are described [in the documentation](https://cloudinit.readthedocs.io/en/latest/topics/contributing.html#submitting-your-first-pull-request)

2022-08-30 18:57 UTC, waldiTM commented
The documentation is in `apt-transport-mirror(1)`.

We want this for Debian, with the following setup for now:

```
$ cat /etc/apt/sources.list.d/debian.sources 
Types: deb deb-src
URIs: mirror+file:///etc/apt/mirrors/debian.list
Suites: bookworm bookworm-updates bookworm-backports
Components: main

Types: deb deb-src
URIs: mirror+file:///etc/apt/mirrors/debian-security.list
Suites: bookworm-security
Components: main

$ cat /etc/apt/mirrors/debian.list 
http://debian-archive.trafficmanager.net/debian

$ cat /etc/apt/mirrors/debian-security.list 
http://debian-archive.trafficmanager.net/debian-security
```

The main advantage is, you can just update the mirrors files, without rewriting the whole sources.list (which requires the distribution name, which is not really available at this step in a Debian system).

For later we intend to also add the fallback mirror, but `apt` currently jokes on non-available mirrors a bit ([#1017899](https://bugs.debian.org/1017899)). This would be then something like:
```
http://debian-archive.trafficmanager.net/debian prio:1
http://deb.debian.org/debian
```

Does this make it more clear?

2022-08-31 19:57 UTC, TheRealFalcon requested changes
Thanks @waldiTM , yes, that helps a lot.

The code looks good overall, but it looks like some linting checks are failing.

Also, can we change the name of `enable_mirrors_files` option to `generate_mirrorlists` and add some more detail to the schema description? The schema description will be the only documentation for this, so it'd be good to explain exactly what happens when you enable this option. It'd be good to mention which files get written and that they contain the PRIMARY and SECURITY mirror info.

Also, we would still need the CLA before we can merge.

2022-09-01 18:04 UTC, waldiTM commented
I did the changes and added more details to the schema description.

For the CLA, that is being worked on by my employer. For now I'll add this that way to the package in Debian, as we need it there now.

2022-09-23 17:42 UTC, TheRealFalcon commented
@waldiTM , any updates on the CLA?

2022-10-16 00:06 UTC, closed without merging

2022-10-16 14:52 UTC, TheRealFalcon commented
@waldiTM , we should be able to re-open this at any time. Please do ping if/when you're able to sign the CLA.