tests: Drop httpretty in favor of responses
canonical/cloud-init pull request #1720
Opened 2022-09-07 18:53 UTC by aciba90

## Proposed Commit Message

```
tests: Drop httpretty in favor of responses
```

## Additional Context

[SC-937](https://warthogs.atlassian.net/browse/SC-937)
After this PR, we could drop `python3-httpretty` from `debian/control` in `ubuntu/<series>` branches.

## Test Steps

`tox`

## Checklist:

 - [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/contributing.html)
 - [x] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any documentation accordingly

2022-09-16 21:24 UTC, TheRealFalcon requested changes
Just one comment to remove, but otherwise looks good!

2022-09-16 21:24 UTC, TheRealFalcon commented on tests/unittests/sources/test_scaleway.py
> +        # import pdb; pdb.set_trace()
Let's remove this line.

2022-09-19 09:14 UTC, aciba90 commented on tests/unittests/sources/test_scaleway.py
> +        # import pdb; pdb.set_trace()
Oops, you got me there :)

2022-09-19 09:14 UTC, aciba90 commented
> Just one comment to remove, but otherwise looks good!

Fixed, thanks for the review, @TheRealFalcon. Ready to be reviewed.

2022-09-19 13:30 UTC, TheRealFalcon approved these changes
@aciba90 , good work. Can you also put up PRs for our packaing?

2022-09-19 13:30 UTC, merged

2022-09-19 16:43 UTC, aciba90 commented
> @aciba90 , good work. Can you also put up PRs for our packaing?

Sure, thanks! [SC-1258](https://warthogs.atlassian.net/browse/SC-1258) created to represent that.