add Anolis support
canonical/cloud-init pull request #1889
Opened 2022-12-05 03:29 UTC by weidongkl

## Proposed Commit Message
Add [Anolis](https://openanolis.cn/) OS support

2022-12-05 16:27 UTC, igalic requested changes
these lists should be alphabetical

(i might have missed some)

2022-12-05 16:27 UTC, igalic commented on cloudinit/distros/__init__.py
> +        "anolis",
this list should be alphabetical

2022-12-05 16:27 UTC, igalic commented on cloudinit/net/sysconfig.py
> +    "anolis",
this list should be alphabetical

2022-12-05 16:27 UTC, igalic commented on cloudinit/util.py
> +            "anolis",
this list should be alphabetical

2022-12-05 16:27 UTC, igalic commented on config/cloud.cfg.tmpl
> +                             "miraclelinux", "rhel", "rocky", "anolis", "virtuozzo" ] %}
this list should be alphabetical

2022-12-05 16:27 UTC, igalic commented on systemd/cloud-init-generator.tmpl
> +{% if variant in ["almalinux", "centos", "cloudlinux", "eurolinux", "fedora", "anolis",
this list should be alphabetical

2022-12-05 16:27 UTC, igalic commented on systemd/cloud-init.service.tmpl
> +{% if variant in ["almalinux", "centos", "cloudlinux", "eurolinux", "fedora", "anolis",
this list should be alphabetical

2022-12-05 16:27 UTC, igalic commented on tests/unittests/test_cli.py
> +                    "opensuse, photon, rhel, rocky, anolis, sles, ubuntu, virtuozzo",
this list should be alphabetical

2022-12-05 16:27 UTC, igalic commented on tests/unittests/test_util.py
> +REDHAT_RELEASE_ANOLIS_8 = "Anolis OS 8.2"
this list should be alphabetical

2022-12-05 16:27 UTC, igalic commented on tests/unittests/test_util.py
> +            ({"system": "linux", "dist": ("anolis",)}, "anolis"),
this list should be alphabetical

2022-12-05 16:27 UTC, igalic commented on tools/read-dependencies
> +    'anolis': 'redhat',
this list should be alphabetical

2022-12-05 16:27 UTC, igalic commented on tools/render-cloudcfg
> +        "anolis",
this list should be alphabetical

2022-12-06 15:03 UTC, TheRealFalcon reviewed
Thanks for the contribution. Do you have any logs/examples of cloud-init running on Anolis with these changes?

2022-12-22 10:11 UTC, igalic commented
given that the cloud-init team is on holidays, maybe this bot should take a break too

2023-01-13 00:03 UTC, closed without merging