ci: doc to gh actions
canonical/cloud-init pull request #1951
Opened 2023-01-10 23:31 UTC by holmanb

```
test: move doc test from travis to actions

Changes:
- drop unnecessary setuptools pin
- use 22.04 system Python 3.10
```

## Additional Context
Makes doc failures visible sooner via gh actions, plus reduce CI bill. This is mostly just copy / paste from existing gh actions tests and the current travis test - low value / low effort.

2023-01-11 00:38 UTC, TheRealFalcon requested changes
This might be a little pedantic, but I think we should ensure we're using the same python version that rtd uses to build the docs. In the past, because of dependency issues, we've had issues where local/CI passes but rtd fails on a different python version. That's probably much less likely to happen after removing the old sphinx pins, but I still think it'd make our CI better.

2023-01-11 00:38 UTC, TheRealFalcon commented on .github/workflows/check_format.yml
> +          make check_spelling
Nit: these last two lines would be better as their own run commands.

2023-01-11 09:08 UTC, s-makin approved these changes
Definitely a nice idea, avoiding the "install python" step that it does every time. Anything that makes the process faster or more efficient gets a thumbs up from me.

2023-01-11 13:55 UTC, holmanb commented
> This might be a little pedantic, but I think we should ensure we're using the same python version that rtd uses to build the docs. In the past, because of dependency issues, we've had issues where local/CI passes but rtd fails on a different python version. That's probably much less likely to happen after removing the old sphinx pins, but I still think it'd make our CI better.

I will do that, but it may drift since RTD only allows configuring [Major.Minor version](https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python). I see the most recent [build used 3.10.8](https://readthedocs.org/projects/cloudinit/builds/19129720/).

2023-01-12 15:14 UTC, TheRealFalcon approved these changes
LGTM. With the python version I'm mostly concerned about major.minor.

2023-01-12 15:19 UTC, holmanb commented
> LGTM. With the python version I'm mostly concerned about major.minor

Ah, I guess I was confused about that then, since Jammy already had the same major.minor as RTD.

2023-01-12 15:21 UTC, merged