Set ownership for new folders
canonical/cloud-init pull request #1980
Opened 2023-01-26 15:43 UTC by zhan9san

## Proposed Commit Message

```
summary: Set ownership for new folders in Write Files Module

The parent directory would be created automatically if it does not exist. But the ownership of newly-created parent directory would always be root.

With this change, it would be set the same as `owner`.

LP: #1990513
```

## Additional Context

## Test Steps

```yaml
write_files:
  - path: /home/ubuntu/.help/file-in.txt
    content: |
      hi in
    owner: 'ubuntu:ubuntu'
    permissions: '0644'
    defer: true
```

With this change, the owner of `/home/ubuntu/.help`  would be `ubuntu`.
Without this change, the owner of `/home/ubuntu/.help`  would be `root`.

## Checklist:

 - [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/contributing.html)
 - [x] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any documentation accordingly

2023-01-26 18:11 UTC, holmanb requested changes
Thanks for the PR and signing the CLA @zhan9san! At a glance this looks pretty good.

I think we should also update the schema definition for `owner` from: `Optional owner:group to chown on the file. Default: root:root.` to something like `Optional owner:group to chown on the file and new directories. Default: root:root.`

2023-01-26 19:47 UTC, igalic commented
n.b.: BSDs don't have a `root` group.
easiest portability thing would be to use "0"

2023-01-27 17:38 UTC, zhan9san commented
@holmanb Thanks for your suggestion. The owner description in schema has been changed as well. Please help review it and approve ci jobs.

@igalic Thanks for your review. Yes, you are right. BSD is an exception.

But I don't think 0 is a good choice. As the users always specify the name instead of id in owner.

2023-01-27 19:44 UTC, igalic commented
ah, in that case, we can just ignore what i said. I thought this was not us providing defaults.
is it's not, we can assume the users know what they're doing ;) and if not, they'll find out on the first run.

2023-01-31 16:12 UTC, holmanb requested changes
Thanks, @zhan9san, for the updates. I have one real objection to the current implementation, but I think it should be relatively simple to change using something like `pathlib.Path`'s `parts` or `parent` rather than a recursive walk of all files.

2023-02-16 19:49 UTC, holmanb commented
Any updates on this @zhan9san?

2023-02-18 09:17 UTC, zhan9san commented
Thanks for your review.
I was a little busy last two weeks.

I'll do it tomorrow

2023-02-20 10:33 UTC, zhan9san commented
@holmanb 

Please help review it again.

2023-02-20 16:47 UTC, holmanb requested changes

2023-02-21 01:49 UTC, zhan9san commented on cloudinit/util.py
> +    """Get non exist parent dir."""
Thanks for your review.

The return value should be `/usr/a` not `/usr`, which is updated in new commit.

2023-02-21 01:49 UTC, zhan9san commented on cloudinit/util.py
> +    if recursive and os.path.isdir(fname):
It's dropped in new commit.

2023-02-21 15:37 UTC, holmanb approved these changes
LGTM! Thanks for this PR. Once CI completes I'll merge.

2023-02-21 15:39 UTC, merged