datasource: Optimize datasource detection, fix bugs
canonical/cloud-init pull request #2060
Opened 2023-03-07 00:31 UTC by holmanb

```
datasource: Optimize datasource detection, fix bugs

Commit d1ffbea556a06105 enabled skipping python datasource detection on OpenStack when no other datasources (besides DataSourceNone) can be discovered. This allowed one to override detection, which is a requirement for OpenStack Ironic which does not advertise itself to cloud-init.

Since no further datasources can be detected at this stage in the code, this pattern can be generalized to other datasources to facilitate troubleshooting or providing a general workaround runtime detection bugs.

Additionally, this pattern can be extended to kernel commandline datasource definition. Since kernel commandline is highest priority of the configurations, it makes sense to override python code datasource detection as well.

```

## Additional Context
Continues work in d1ffbea556a06105d1ade88b4143ad43f53692c4 and https://github.com/canonical/cloud-init/pull/2044.

2023-03-10 22:16 UTC, TheRealFalcon requested changes
I like this change and the PR overall looks really good. I have a few minor inline comments.

> Docs will come in a separate PR

Ticket number or I don't believe you :wink:

2023-03-10 22:16 UTC, TheRealFalcon commented on tests/unittests/sources/test_cloudsigma.py
> +        # fails on python 3.6
Why?

2023-03-10 22:16 UTC, TheRealFalcon commented on tests/integration_tests/datasources/test_detect_openstack.py
> +@pytest.mark.lxd_container
This can't actually run on lxd_container right?

2023-03-11 00:29 UTC, holmanb commented on cloudinit/sources/__init__.py
> +        ds_parse_1 = re.search(r"ci\.ds=([a-zA-Z]+) ", cmdline)
> Can datasource be the last thing on the cli?

Yes

> r"ci\.ds=([a-zA-Z]+)( |$)"

+1 Nice suggestion.

> In my testing, it detects the space before the end of line, but I'm not sure if there's a better way to indicate that as taking precedence.

I don't follow what you're saying about precedence.

> Also does it make sense to capture more whitespace than a space?
Are you talking about different kinds of whitespace here? As in, if someone separates arguments with newlines or tabs or something weird like that?

2023-03-11 00:30 UTC, holmanb commented on cloudinit/sources/__init__.py
> +                "Machine is configured by the kernel commandline to run on "
> slightly more intuitive here

Heh, not sure what I was thinking here. Returning log messages as an implicit truthy value is not intuitive, agreed.

2023-03-11 02:59 UTC, TheRealFalcon commented on cloudinit/sources/__init__.py
> +        ds_parse_1 = re.search(r"ci\.ds=([a-zA-Z]+) ", cmdline)
> I don't follow what you're saying about precedence.

Yeah, nevermind...thinking about it again my question doesn't make sense.

> Are you talking about different kinds of whitespace here? As in, if someone separates arguments with newlines or tabs or something weird like that?

Correct

2023-03-11 03:25 UTC, holmanb commented on cloudinit/sources/__init__.py
> +        ds_parse_1 = re.search(r"ci\.ds=([a-zA-Z]+) ", cmdline)
> > Are you talking about different kinds of white space here? As in, if someone separates arguments with newlines or tabs or something weird like that?

> Correct

+1 I'll cook something up.

2023-03-18 04:45 UTC, holmanb commented on tests/unittests/sources/test_cloudsigma.py
> +        # fails on python 3.6
Nevermind, dropped these

2023-03-18 04:55 UTC, holmanb commented
> > Docs will come in a separate PR
> 
> Ticket number or I don't believe you

[Sure](https://warthogs.atlassian.net/browse/SC-1457) :-)

I think I've addressed everything. If tests pass I think this is ready for another round of review.

2023-03-20 01:23 UTC, TheRealFalcon approved these changes
LGTM!

2023-03-20 01:24 UTC, merged