handler: report errors on skipped merged cloud-config.txt parts
canonical/cloud-init pull request #2150
Opened 2023-04-29 22:10 UTC by blackboxsw

## Proposed Commit Message
```
Log errors instead of warnings on skipped/invalid cloud-config parts.

Also add error comments to the merged /v/l/c/.../cloud-config.txt.

Error bread crumb comments also permit cloud-init schema to bette represent failures to load user-data parts when either MIME messages or jinja templates represent non-YAML or unparseable content.

LP: #1999952
```

## Additional Context

## Test Steps

## Checklist:

 - [ ] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/contributing.html)
 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any documentation accordingly

2023-05-10 18:31 UTC, TheRealFalcon requested changes
https://github.com/canonical/cloud-init/pull/2132/files#diff-3dab74160d0d2e18837e4c271eb03209be4263cf51d44cb8ca78bb739fd3f68cR1283 
is causing this to not work. We need to fetch the datasource before we can call `get_ipath()`.

If I fix that manually I can see the --annotate changes, but I'm still unsure how to trigger the exception handling in `cloud_config.py`.

2023-05-10 18:31 UTC, TheRealFalcon commented on cloudinit/handlers/cloud_config.py
> +            msg = f"Failed at merging cloud config part from {filename}: {err}"
How can I make this happen?

2023-05-10 21:16 UTC, TheRealFalcon commented
> https://github.com/canonical/cloud-init/pull/2132/files#diff-3dab74160d0d2e18837e4c271eb03209be4263cf51d44cb8ca78bb739fd3f68cR1283
is causing this to not work. 

Also noticed this is causing [integration tests to fail](https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-bionic-ec2/243/#showFailuresLink). If you think it'll take a bit to get this PR ready, I'd rather merge the fix separately so our test jobs can pass sooner.

2023-05-31 04:44 UTC, blackboxsw commented on cloudinit/handlers/cloud_config.py
> +            msg = f"Failed at merging cloud config part from {filename}: {err}"
I pushed an integration-test for this
```
make deb
CLOUD_INIT_CLOUD_INIT_SOURCE=cloud-init_23*.deb .tox/integration-tests/bin/pytest tests/integration_tests/test_multi_part_user_data_handling.py::test_mime_with_error_parts
```

2023-05-31 04:48 UTC, blackboxsw commented
> > https://github.com/canonical/cloud-init/pull/2132/files#diff-3dab74160d0d2e18837e4c271eb03209be4263cf51d44cb8ca78bb739fd3f68cR1283
> > is causing this to not work.
> 
> Also noticed this is causing [integration tests to fail](https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-bionic-ec2/243/#showFailuresLink). If you think it'll take a bit to get this PR ready, I'd rather merge the fix separately so our test jobs can pass sooner.

Resolved this issue with previous commit 73f34575da

2023-05-31 04:50 UTC, blackboxsw commented on cloudinit/config/schema.py
> +    decoded_content = decode_binary(content)
Adapted the code to decode once and expect str instead of bytes throughout.

2023-06-01 19:50 UTC, TheRealFalcon requested changes
I left some minor inline comments, but looks good overall.

2023-06-01 19:50 UTC, TheRealFalcon commented on tests/integration_tests/test_multi_part_user_data_handling.py
> +    assert re.findall(RE_EXPECTED_SCHEMA_ANNOTATE, result.stdout)
`RE_EXPECTED_SCHEMA_ANNOTATE` has a trailing newline, but `result.stdout` doesn't, so they don't match. Adding a `.strip()` to both of them matches it for me.

2023-06-01 19:50 UTC, TheRealFalcon commented on cloudinit/config/schema.py
> +    content: str, annotate: bool
`annotate` isn't used in this function.

2023-06-01 19:50 UTC, TheRealFalcon commented on cloudinit/config/schema.py
> +                    schema_errors=errors + e.schema_errors,
Just based on typing, `e.schema_errors` can return `None`, so it's possible we could get a `TypeError` here adding a list to None. However, I haven't fully grokked all error paths, so if that's not a realistic worry, feel free to ignore.

2023-06-19 18:14 UTC, TheRealFalcon approved these changes
Just the lint error now, but otherwise LGTM!

2023-06-20 21:35 UTC, merged