cc_rsyslog: Refactor for better multi-platform support
canonical/cloud-init pull request #4119
Opened 2023-05-17 20:51 UTC by igalic

## Proposed Commit Message

```
cc_rsyslog: Refactor for better multi-platform support

- remove Hash key redirection
- copy basic multi-distro config from cc_ntp
- add optional installation
- enable and start services
- on BSD: disable Base system syslog

Sponsored by: The FreeBSD Foundation

Fixes: #3250
LP: #1798055
```

## Additional Context

## Test Steps

## Checklist:

 - [ ] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/contributing.html)
 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any documentation accordingly

2023-05-23 15:03 UTC, igalic reviewed
This PR, which was meant as a short distraction, turned into a massive yak shave.

here are some guide posts for reviewers.

2023-05-23 15:03 UTC, igalic commented on cloudinit/config/cc_rsyslog.py
> +def disable_and_stop_bsd_base_syslog(cloud: Cloud) -> None:
this function is a mess, but it *is* correct.

2023-05-23 15:03 UTC, igalic commented on cloudinit/config/cc_rsyslog.py
> +def install_rsyslog(install_func, packages=None, check_exe="rsyslog"):
stolen from cc_ntp

2023-05-23 19:09 UTC, TheRealFalcon requested changes
Nice change overall. I left some inline comments.

One major concern...the rsyslog module runs early enough in boot that, at least on systemd systems, it's considered to be before network is even online. I don't think we should be reaching out to the internet to do package installs in this time frame. I just tried running cloud-init locally where rsyslog isn't installed, and it appears that apt is hanging trying to install it. I think at the very least we need to make installation a configuration option that defaults to false.

2023-05-23 22:43 UTC, igalic commented
> One major concern...the rsyslog module runs early enough in boot that, at least on systemd systems, it's considered to be before network is even online. I don't think we should be reaching out to the internet to do package installs in this time frame. I just tried running cloud-init locally where rsyslog isn't installed, and it appears that apt is hanging trying to install it. I think at the very least we need to make installation a configuration option that defaults to false.

On FreeBSD, cc_rsyslog runs well after we have a network connection, so package installation is not a problem.

2023-05-24 11:06 UTC, igalic commented on cloudinit/config/cc_rsyslog.py
> +def disable_and_stop_bsd_base_syslog(cloud: Cloud) -> None:
function now less messy

2023-05-24 11:06 UTC, igalic commented on cloudinit/config/cc_rsyslog.py
> +def disable_and_stop_bsd_base_syslog(cloud: Cloud) -> None:
(and still correct)

2023-05-25 14:43 UTC, TheRealFalcon requested changes
> On FreeBSD, cc_rsyslog runs well after we have a network connection, so package installation is not a problem.

That's fine, but we can't start breaking things on Linux. As-is, the install will run regardless of the OS we're on. Without this change, if rsyslog wasn't already installed, you already had a problem in that you were trying to run a module for a service that wasn't installed, but the change here can compound the problem and can prevent cloud-init from completing. Additionally, if somebody wants to start running rsyslog on a distro that doesn't have it pre-installed, hitting these install issues is not a great experience.

I think we need to add one more config option, something like `install_syslog` that defaults to False along with a documentation note in the module mentioning that due to rsyslog running so early in boot, installation is not supported for every distro.

2023-05-25 15:49 UTC, igalic commented on cloudinit/config/cc_rsyslog.py
> +    try:
*\*points at Erlang's and Common Lisp's error handling\**

can we have some of this?

2023-05-30 19:01 UTC, TheRealFalcon requested changes
Just a minor doc change request, but other LGTM!

Doc standard these days is to put the default for a config value in the schema rather than in the module description. Also, I think it makes more sense for `install_rsyslog` to sit above the other new options as they both depend on that one. I put these suggestions in the following patch:
```diff
diff --git a/cloudinit/config/cc_rsyslog.py b/cloudinit/config/cc_rsyslog.py
index a61ae943c..5ec99f0b0 100644
--- a/cloudinit/config/cc_rsyslog.py
+++ b/cloudinit/config/cc_rsyslog.py
@@ -30,10 +30,9 @@ This module configures remote system logging using rsyslog.
 Configuration for remote servers can be specified in ``configs``, but for
 convenience it can be specified as key value pairs in ``remotes``.
 
-This module can install rsyslog ``packages`` (Default: ``["rsyslog"]``) if
-``check_exe`` (Default: ``"rsyslogd"``) cannot be found.
-On many systems, this may not work, because networking isn't up yet.
-That's why ``install_rsyslog`` defaults to ``False``.
+This module can install rsyslog if not already present on the system using the
+``install_rsyslog``, ``packages``, and ``check_exe`` options. Installation
+may not work on systems where this module runs before networking is up.
 
 .. note::
     On BSD cloud-init will attempt to disable and stop the base system syslogd.
diff --git a/cloudinit/config/schemas/schema-cloud-config-v1.json b/cloudinit/config/schemas/schema-cloud-config-v1.json
index c6a08b237..6466e541c 100644
--- a/cloudinit/config/schemas/schema-cloud-config-v1.json
+++ b/cloudinit/config/schemas/schema-cloud-config-v1.json
@@ -2373,9 +2373,14 @@
                 }
               ]
             },
+            "install_rsyslog": {
+              "default": false,
+              "description": "Install rsyslog. Default: ``false``",
+              "type": "boolean"
+            },
             "check_exe": {
               "type": "string",
-              "description": "The executable name for the rsyslog daemon.\nFor example, ``rsyslogd``, or ``/opt/sbin/rsyslogd`` if the rsyslog binary is in an unusual path."
+              "description": "The executable name for the rsyslog daemon.\nFor example, ``rsyslogd``, or ``/opt/sbin/rsyslogd`` if the rsyslog binary is in an unusual path. This is only used if ``install_rsyslog`` is ``true``. Default: ``rsyslogd``"
             },
             "packages": {
               "type": "array",
@@ -2383,12 +2388,7 @@
                 "type": "string"
               },
               "uniqueItems": true,
-              "description": "List of packages needed to be installed for rsyslog."
-            },
-            "install_rsyslog": {
-              "default": false,
-              "description": "Install rsyslog. Default: ``false``",
-              "type": "boolean"
+              "description": "List of packages needed to be installed for rsyslog. This is only used if ``install_rsyslog`` is ``true``. Default: ``[rsyslog]``"
             }
           }
         }
```
```

2023-05-30 23:59 UTC, TheRealFalcon approved these changes
LGTM!

2023-05-31 00:01 UTC, merged