Sc 1452 persist run combined cloud config json
canonical/cloud-init pull request #4192
Opened 2023-06-20 21:13 UTC by blackboxsw

## Proposed Commit Message
```
instance-data: write /run/cloud-init/merged-cloud-config.json

Persist the merged_cloud_config key as a new file to aid in
discovery or provided configuration settings.

The file /run/cloud-init/merged-cloud-config.json represents the
full configuration presented to cloud-init which layers config
settings in the following priority order:
1. default config: cloudinit.settings.CFG_BUILTIN
2. merged_system_cfg: config from file-system /etc/cloud and
    /etc/cloud.cfg.d
3. cloud-specific metadata
4. cloud-specific vendor-data, vendor-data2
5. cloud-specific user-data
    
Configuration keys present in earlier sources are overridden by
keys in later sources.
```

## Additional Context

## Test Steps

## Checklist:

 - [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/contributing.html)
 - [x] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any documentation accordingly

2023-06-29 18:42 UTC, dbungert commented
Testing notes:

* using this branch, staged into the Subiquity snap, already fixes https://bugs.launchpad.net/subiquity/+bug/2022102 - though I don't know if that's the result of this branch directly or the branch it's based upon

* using this branch, built with `./packages/bddeb -S -d --release jammy` then using any suitable build strategy for a binary package, and staging into the host image of the mantic-live-server ISO, indeed produces the desired JSON at `/run/cloud-init/combined-cloud-config.json`.  Thanks!

2023-06-29 19:14 UTC, dbungert commented
I created a proof of concept branch to consume the data from this location.  https://github.com/dbungert/subiquity/pull/new/consume-combined-cloud-config

The change is straightforward and works nicely .

2023-07-03 11:40 UTC, aciba90 requested changes
Overall looks great thanks. Nice touch moving functions to `atomic_helper.py`.

There are a couple of warnings in `tests/integration_tests/modules/test_jinja_templating.py::test_substitution_in_etc_cloud` which need some caring. I think they are tests problems, but I didn't dive into them.

2023-07-03 11:40 UTC, aciba90 commented on tests/unittests/test_data.py
Thanks for migrating this to pytest.

2023-07-03 20:58 UTC, blackboxsw commented
> There are a couple of warnings in `tests/integration_tests/modules/test_jinja_templating.py::test_substitution_in_etc_cloud` which need some caring. I think they are tests problems, but I didn't dive into them.

Yes, the value we were sourcing in this integration test in `echo {{merged_cfg._doc}}` now has a colon in the prefix `DEPRECATED: `  which lead to interpreting the jinja rendered content as invalid #cloud-config YAML dict instead of list.

I've used the intended not-deprecated key `merged_system_cfg` which doesn't cause this testing problem.

```
87.42s setup    tests/integration_tests/modules/test_jinja_templating.py::test_substitution_in_etc_cloud
11.60s call     tests/integration_tests/modules/test_jinja_templating.py::test_substitution_in_etc_cloud
0.65s teardown tests/integration_tests/modules/test_jinja_templating.py::test_substitution_in_etc_cloud
=================== 1 passed, 2 warnings in 99.67s (0:01:39) ===================
___________________________________ summary ____________________________________
  integration-tests: commands succeeded
  congratulations :)
```

2023-07-04 00:57 UTC, TheRealFalcon approved these changes
One more integration test update needed, but I'll trust you can apply that on your own. Other than that, +1 from me.

2023-07-04 00:57 UTC, TheRealFalcon commented on tests/integration_tests/modules/test_jinja_templating.py
> +        " - echo '{{merged_system_cfg._doc}}' > /var/tmp/bootcmd_output\n"
Same change needed on line 20 too

2023-07-04 11:10 UTC, aciba90 approved these changes

2023-07-05 17:16 UTC, merged