Overhaul module reference page
canonical/cloud-init pull request #4237
Opened 2023-07-10 10:40 UTC by s-makin

```
Module reference page was previously long lists of descriptions that were hard to consume.
- Add tabs to split up sections within module reference
- Tab syncing is an option, but may not be helpful here so left it off by default
- Subheadings can't be used within tabs, so changed headers in cc_ssh module description
```

2023-07-11 00:08 UTC, igalic commented
is there a way to preview this?

2023-07-11 21:09 UTC, TheRealFalcon requested changes
Fancy! There's a few small inline issues, but otherwise LGTM.

Tests need to be updated. I'm assuming you want some help with that?

2023-07-11 21:09 UTC, TheRealFalcon commented on cloudinit/config/schema.py
> +            prefix=f"Cloud config schema deprecations: ",
f-string isn't needed here

2023-07-12 08:19 UTC, s-makin commented
> Tests need to be updated. I'm assuming you want some help with that?

Thanks for the review, I'll fix the nits - I made a bunch of experimental changes in trying to solve the "indentation" errors, and definitely forgot to undo those f-strings. 

Yes please on the help with tests!

2023-07-21 21:20 UTC, TheRealFalcon commented
@s-makin , I rebased the branch and fixed tests. I took the liberty of pushing directly to your branch. If that's a problem, I can always undo it. If any other CI fails I can take a look.

2023-07-25 15:25 UTC, merged