Ubuntu/devel
canonical/cloud-init pull request #4264
Opened 2023-07-20 16:01 UTC by holmanb

```
Remove NetworkManager hook

LP: #2027861
```

2023-07-21 07:26 UTC, CalvoM approved these changes
LGTM

2023-07-24 07:49 UTC, aciba90 approved these changes
+1.

I guess this has to be replicated on F, K and J, right?

2023-07-24 07:52 UTC, aciba90 requested changes
Add a separated commit explaining what has been done in `d/changelog`, please.

2023-07-24 21:08 UTC, TheRealFalcon commented
`* d/cloud-init.maintscript: Remove the unused hook-network-manager conffile` is the changelog entry I used in #4286 if you wanna steal it

2023-07-25 15:51 UTC, TheRealFalcon commented
while this branch is up, we may want to cherry-pick in the python3-passlib build-depends in #4286 .

2023-07-26 04:26 UTC, TheRealFalcon approved these changes
we jumped from 1 to 3, but not a big deal since it won't get released. We can do the upstream snapshot separately if that's easier.

2023-07-26 14:49 UTC, merged