patch: Retain old groups in default user template
canonical/cloud-init pull request #4265
Opened 2023-07-20 17:11 UTC by holmanb

```
patch: Retain old groups in default user template
```

## Additional Context
I just merged https://github.com/canonical/cloud-init/pull/4258, for which this patch retains old behavior.

https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1923363

2023-07-20 18:33 UTC, TheRealFalcon requested changes
Don't forget the d/changelog entry

2023-07-20 21:17 UTC, holmanb commented
@TheRealFalcon Thanks for the review. I'll open against lunar and focal once this is approved.

2023-07-20 22:03 UTC, TheRealFalcon commented
Sorry, didn't really look super thoroughly the last time.

I think we need an upstream snapshot first. How can we have a patch against code that doesn't actually exist yet in the branch? After that, we need to generate a quilt patch, not just a diff. It needs a DEP-3 header and a reference in `d/patches/series`.

See https://github.com/canonical/uss-tableflip/blob/main/doc/ubuntu_release_process.md#adding-a-quilt-patch-to-debianpatches (or https://wiki.debian.org/UsingQuilt).

2023-07-24 21:14 UTC, TheRealFalcon commented
If #4286 merges we can close this one

2023-07-25 20:53 UTC, TheRealFalcon commented
Closing as it was incorporated in #4286 .

2023-07-25 20:53 UTC, closed without merging