Jammy debian/cloud-init.templates: enable Akamai by default
canonical/cloud-init pull request #4371
Opened 2023-08-21 13:31 UTC by aciba90

## Do not squash

## Additional context

https://github.com/canonical/cloud-init/issues/4362
Continuation of https://github.com/canonical/cloud-init/pull/4167

2023-08-21 13:37 UTC, aciba90 commented
After approval, I will replicate this in:

- [ ] lunar
- [ ] focal

2023-08-21 16:02 UTC, blackboxsw requested changes
@aciba90 thanks, two minor notes, otherwise +1

2023-08-22 11:36 UTC, aciba90 commented on debian/changelog
> +    Add Akamai to the default templates as enabled by default.
Applied, thanks.

2023-08-22 11:36 UTC, aciba90 commented on debian/cloud-init.templates
> +__Choices: NoCloud: Reads info from /var/lib/cloud/seed only, ConfigDrive: Reads data from Openstack Config Drive, OpenNebula: read from OpenNebula context disk, DigitalOcean: reads data from Droplet
Applied, thanks.

2023-08-22 11:36 UTC, aciba90 commented
> @aciba90 thanks, two minor notes, otherwise +1

Applied, thanks!

2023-08-25 03:14 UTC, blackboxsw approved these changes
LGTM, @aciba90, you may need to rebase on upstream/ubuntu/focal before you push to upstream as I just pushed the separate PR fixing the daily build recipe too.

2023-08-25 12:51 UTC, merged