Prevent from wrongly interpreting cc: in a BOOTIF=mac  as config yaml
canonical/cloud-init pull request #4477
Opened 2023-10-02 04:09 UTC by jjqq2013

When a mac address contains cc, such as
```
01:02:03:04:cc:f4
```

and when the kernel command line is
```
.... BOOTIF=01:02:03:04:cc:f4 ...
```

then cloudinit will wrongly think that 
```
f4 ...
```
are a cloudinit config yaml, then the yaml parser fails.

Normally this will not have a problem, but if the kernel command line embeds an important cloudinit instruction such as runcmd, then it will not be run, such as
```
... ds=nocloud cc: datasource_list: [NoCloud] end_cc cc: runcmd: [[echo,a]] end_cc BOOTIF=01:02:03:04:cc:f4
```

I have tested on a real UEFI PXE booted liveos.

## Proposed Commit Message

```
summary: no more than 70 characters

A description of what the change being made is and why it is being
made, if the summary line is insufficient.  The blank line above is
required. This should be wrapped at 72 characters, but otherwise has
no particular length requirements.

If you need to write multiple paragraphs, feel free.

Fixes GH-NNNNN (GitHub Issue number. Remove line if irrelevant)
LP: #NNNNNN (Launchpad bug number. Remove line if irrelevant)
```

## Additional Context

## Test Steps

## Checklist:

 - [ ] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/contributing.html)
 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any documentation accordingly

2023-10-02 22:53 UTC, igalic requested changes
let's and a comment and/or a test case to ensure we know why this exists

2023-10-03 15:43 UTC, TheRealFalcon commented on cloudinit/util.py
> +    tag_begin = " cc:"
Since it is valid for the line to begin with `cc:`, this won't work in that case.

I'm tempted to replace this entire section with regex parsing.

2023-10-22 05:46 UTC, holmanb commented
Doesn't `cc:` get parsed over ds `ds-identify` too? We might want to check if a related bug exists there too.

2023-10-23 06:09 UTC, jjqq2013 commented
@TheRealFalcon  hi, sorry I don't have time to create a full PR, It would be great if you can take over this ticket.

2023-10-23 06:13 UTC, jjqq2013 commented
@holmanb 
> Doesn't cc: get parsed over in ds-identify too? We might want to check if a related bug exists there too.

When I test the case `... ds=nocloud cc: datasource_list: [NoCloud] end_cc cc: runcmd: [[echo,a]] end_cc BOOTIF=01:02:03:04:cc:f4`, I did not find any error in ds-identity related output.
I remember that when ds-identify get called, cloud-init has finished the parsing of command line, so I think the issue does not affect in ds-identy itself.

2023-10-23 06:22 UTC, jjqq2013 commented
Thanks all for taking a look at this issue.

@TheRealFalcon 
> Since it is valid for the line to begin with cc:, this won't work in that case.
> I'm tempted to replace this entire section with regex parsing. Is that something you'd be interested in doing?

The parser read the whole kernel command line, such as
case1:
```
... BOOTIF=01:02:03:04:cc:f4 ...
```
case2:
```
... cc: cloudinit_yml_here
```
case3:
```
cc: cloudinit_yml_here
```

You can see that case1 and case2 contains ` cc:`, note the preceding space.

The case3 does not exist unless when someone insanely produced a kernel command line which starts with exactly `cc:`, I don't think that is possible in normal Linux boot protocol.

So the ` cc:` works well (note the preceding space).

And since this issue is a rare issue, no much system pass critical thing such as runcmd via kernel command line,
I think it is not worthy putting much effort to fix this issue such as considering all `<OTHER_WHITE_SPACE>cc:`.

2023-10-23 13:11 UTC, aciba90 commented
Let me take over this one.

2023-10-23 18:57 UTC, TheRealFalcon commented
Thanks for the additional context @jjqq2013 .

@aciba90 , feel free!

2023-10-23 22:27 UTC, holmanb commented
> The case3 does not exist unless when someone insanely produced a kernel command line which starts with exactly cc:, I don't think that is possible in normal Linux boot protocol.

Not only is it possible, it is trivial. Consider:
```bash
root@me:~# sudo kexec -l /boot/vmlinuz-5.15.0-1017-kvm --append 'cc: cloudinit_yml_here cc_end root=PARTUUID=2fec7223-75cc-463c-a987-85456171d574 ro console=tty1 console=ttyS0 panic=-1' --initrd=/boot/initrd.img-5.15.0-1017-kvm
root@me:~# kexec -e


```

(Log back into the instance with the new running kernel)
```
root@me:~# cat /proc/cmdline 
cc: cloudinit_yml_here cc_end root=PARTUUID=2fec7223-75cc-463c-a987-85456171d574 ro console=tty1 console=ttyS0 panic=-1
```
Therefore, as @TheRealFalcon already said, it is valid for the line to begin with cc:. Lets just fix it the right way.

2023-10-25 01:34 UTC, jjqq2013 commented
> Not only is it possible, it is trivial. Consider:
@holmanb thanks for pointing this. Yes, also possible in grub.cfg, normally the kernel command line begins with `root=...`, it is possible that if someone insert 'cc:....' before it, just people are fear of doing that.
```
linux   /boot/vmlinuz-5.4.0-139-generic root=UUID=8e0d54b3-93b0-46e2-99ff-c9f4fbbc9adf ro  console=tty0 console=ttyS0,115200
```

Anyway, it would be beautiful if we can cover all the cases.

2023-10-25 07:41 UTC, aciba90 commented
> Anyway, it would be beautiful if we can cover all the cases.

This is being addressed in https://github.com/canonical/cloud-init/pull/4541.

Please, @jjqq2013, see https://github.com/canonical/cloud-init/pull/4541#pullrequestreview-1695735286. Thanks.

2023-11-07 07:59 UTC, TheRealFalcon commented
Addressed in #4541 . Closing this one.

2023-11-07 07:59 UTC, closed without merging