Clarify boothook docs
canonical/cloud-init pull request #4543
Opened 2023-10-24 00:46 UTC by holmanb

```
Clarify boothook docs
```

## Additional Context
See commit messages for explanations

2023-10-24 09:34 UTC, s-makin approved these changes
I think this makes sense. Thanks for taking the lead on this - I agree it's better not to present these terms without them being explained anywhere, and if the user doesn't need to know about boothooks at all then this definition/term should be avoided except in the dev docs.

2023-10-24 10:15 UTC, aciba90 approved these changes
LGTM, thanks for cleaning this up!

2023-10-25 03:57 UTC, blackboxsw commented on doc/rtd/explanation/boot.rst
> +A part-handler and boothooks will run at this stage.
Let's cross link using the autosectiondocs.
```suggestion
A part-handler and :ref:`boothooks<explanation/format:\`\`cloud-boothook\`\`>`
+will run at this stage.
```

2023-10-25 03:58 UTC, blackboxsw requested changes
MOAR linking FTW. Approved after this changeset.

2023-10-27 19:57 UTC, blackboxsw approved these changes
There was a stray `+` as part of my suggested fix. force-pushed that and +1

2023-10-27 19:59 UTC, merged