tools/render-template: Allow disabling yaml loading
canonical/cloud-init pull request #4564
Opened 2023-10-28 18:45 UTC by holmanb

## Proposed Commit Message

```
tools/render-template: Allow disabling yaml loading
```

2023-10-29 11:49 UTC, igalic approved these changes
that seems most sensible!

2023-10-30 19:08 UTC, blackboxsw requested changes
I `git bisected` this error/behavior down to commit 0044c83512d915137ccc79553b57c0250b0f474f which actually fixed a broken global logging setup relative to tools/render-cloudcfg globally which now allowed render warning logs to `stderr` which had been there during package build for quite a while.

Given that the initial intent of the yaml_load was to validate that the cloud.cfg we packaged was valid YAML, I think it's worth trying to treat this as a harder error so we downstreams can catch it at package build time and prevent shipping an invalid YAML in `/etc/cloud/cloud.cfg`.   


So, what I think needs to happen here is setup.py should be aware of which files are expected to by YAML and which aren't when rendering from templates. In practice it looks like it's just `/etc/cloud/cloud.cfg`.

In order to allow setup.py to continue to validate the YAML of `/tec/cloud/cloud.cfg` should we grow an option to `setup.render_tmpl` like the following?

```diff
diff --git a/setup.py b/setup.py
index 5fb269655..4344a8312 100644
--- a/setup.py
+++ b/setup.py
@@ -50,7 +50,7 @@ VARIANT = None
 PREFIX = None
 
 
-def render_tmpl(template, mode=None):
+def render_tmpl(template, mode=None, is_yaml=False):
     """render template into a tmpdir under same dir as setup.py
 
     This is rendered to a temporary directory under the top level
@@ -82,6 +82,7 @@ def render_tmpl(template, mode=None):
         cmd_variant = ["--variant", VARIANT]
     if PREFIX:
         cmd_prefix = ["--prefix", PREFIX]
+    cmd_yaml = [] if is_yaml else ["--no-yaml"]
     subprocess.run(
         [
             sys.executable,
@@ -269,7 +270,7 @@ if not in_virtualenv():
         INITSYS_ROOTS[k] = "/" + INITSYS_ROOTS[k]
 
 data_files = [
-    (ETC + "/cloud", [render_tmpl("config/cloud.cfg.tmpl")]),
+    (ETC + "/cloud", [render_tmpl("config/cloud.cfg.tmpl", is_yaml=True)]),
     (ETC + "/cloud/clean.d", glob("config/clean.d/*")),
     (ETC + "/cloud/cloud.cfg.d", glob("config/cloud.cfg.d/*")),
     (ETC + "/cloud/templates", glob("templates/*")),
```

2023-10-30 22:24 UTC, holmanb commented on cloudinit/templater.py
> +    render_template(variant, template, output, False, prefix)
originally created this for compat - realize now that this function is only called in tests so I'll just strike this extra signature

2023-10-30 22:48 UTC, holmanb commented
> I git bisected this error/behavior down to commit https://github.com/canonical/cloud-init/commit/0044c83512d915137ccc79553b57c0250b0f474f which actually fixed a broken global logging setup relative to tools/render-cloudcfg globally which now allowed render warning logs to stderr which had been there during package build for quite a while.

I was curious why that happened. Fixing one bug exposed another. Nice.

> Here's a diff that'd only build INITSYS_FILES for the init-system provided.

Funky use for lambdas, I like it.

@blackboxsw I think I've addressed everything, thanks for the review.

2023-10-31 15:07 UTC, blackboxsw approved these changes
LGTM thanks for the fixup.

2023-10-31 18:04 UTC, merged