Support for AIX
canonical/cloud-init pull request #4713
Opened 2023-12-21 13:44 UTC by AkashKTripathi

We are using this Issue to push the Code changes that are needed to provide IBM AIX OS support for the cloud-init.

In multiple location, where the command are specific to IBM AIX, We have inserted the if condition to check the underlying OS.
We are running AIX specific command only if the AIX is running on that system.

2023-12-21 16:19 UTC, igalic commented on cloudinit/sources/DataSourceNoCloud.py
> +            devlist = aix_util.find_devs_with("cd0")
i know the structure in util.py isn't great, but, why aren't you extending that, rather tumač touching every DataSource separately?

2023-12-21 16:22 UTC, igalic commented on config/cloud.cfg
> +# The top level settings are used as module
this file needs to go

2023-12-21 16:25 UTC, igalic commented on sysvinit/aix/cloud-config
> +[ -f /etc/default/cloud-init ] && . /etc/default/cloud-init
other init systems also allow disabling with the existence of a file

2024-01-04 01:03 UTC, holmanb requested changes
Hey @AkashKTripathi,

Thanks for this contribution to cloud-init. As described in the [contribution guide](https://cloudinit.readthedocs.io/en/latest/development/index.html#prerequisites), I'll need you to sign the CLA before this contribution can be accepted.

2024-01-04 02:53 UTC, holmanb commented on cloudinit/cmd/main.py
> +        init.purge_cache(True)
One more comment:

This is a pretty big change to cloud-init. What justification do you have for it? Also, which datasources have you tested this on? Wouldn't this break any user using [nocloud](https://cloudinit.readthedocs.io/en/latest/reference/datasources/nocloud.html#method-1-local-filesystem-labeled-filesystem) with only a `CIDATA` drive?

2024-01-22 20:11 UTC, holmanb commented
@AkashKTripathi Any update on this?

2024-02-13 20:58 UTC, holmanb commented
@AkashKTripathi Is there any interest in making this happen still?

2024-02-14 07:21 UTC, AkashKTripathi commented
> @AkashKTripathi Is there any interest in making this happen still?

Hi @holmanb
we are working on it.  we will update you

2024-03-16 00:19 UTC, closed without merging