timeout parameter for cloud-init --wait  #4059
canonical/cloud-init pull request #4717
Opened 2023-12-23 15:09 UTC by FoRtY-5

## Proposed Commit Message

```
feature: status command doesn't have to block forever

Added `--timeout` flag for `cloud-init status --wait` command to terminate after 
declared amount of seconds.

Fixes GH-#4059
LP: #1999876
```

## Additional Context

Example usage `cloud-init status --wait --timeout 5`
Time to terminate provided in timeout flag might not be 1:1 with real time in seconds because of the time library behavior (I suppose), the implemented solution meant to be clear and readable and also fulfills requirements assumed based on the context from https://irclogs.ubuntu.com/2022/12/15/%23cloud-init.html
## Test Steps

## Checklist

- [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/index.html)
- [ ] I have updated or added any [unit tests](https://cloudinit.readthedocs.io/en/latest/development/testing.html) accordingly
- [x] I have updated or added any [documentation](https://cloudinit.readthedocs.io/en/latest/development/contribute_docs.html) accordingly

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

2023-12-27 18:17 UTC, holmanb commented
I'm still not convinced that this is a real value add. The user can already do this themselves with `cloud-init status` in a loop.

If a timeout happens, the user is going to have to do error handling based on the return code anyways (otherwise their code will be making invalid assumptions). Is that really so hard to do for the typical user of this flag?

I'm not going to say we can't do this, but I am hesitant to add this, since the real users of this are automated scripts, which I would assume have the ability to loop since they also need the ability to do conditional execution.

Thoughts?

2024-01-02 21:50 UTC, FoRtY-5 commented
I think that based on the [conversation](https://irclogs.ubuntu.com/2022/12/15/%23cloud-init.html) it would be handy for testers to use the `cloud-init status --wait` with the `--timeout` flag - without the `--timeout` flag the `--wait` flags blocks the execution of the test until status changes. 
In my opinion it maybe makes sense for testers to have a simple one line command `cloud-init status --wait --timeout SECONDS`, so it makes their job a little bit easier(?)

With that being said I would consider adding this small enhancement to the main branch - personally I don't see a lot of value added to the final product, maybe life of some testers would be a little bit easier after this change.
Consider closing this issue after deciding what to do with this PR. [Issue](https://github.com/canonical/cloud-init/issues/4059)

2024-01-03 00:28 UTC, holmanb commented
Thanks for contributing, @FoRtY-5. Please [add yourself to the cla](https://cloudinit.readthedocs.io/en/latest/development/index.html#prerequisites). Also, this adds code but no tests. Please add test coverage in `tests/integration_tests/cmd/test_status.py` and `tests/unittests/cmd/test_status.py`.

> In my opinion it maybe makes sense for testers to have a simple one line command cloud-init status --wait --timeout SECONDS, so it makes their job a little bit easier(?)

Allowing them to add a flag rather than write their own timeout look on `cloud-init status` makes their job easier. It just also adds code that we have to maintain. And if we're going to give users a new feature lets at least document how to use it correctly.

The point that I'm trying to make is that every caller of this flag will absolutely need to know whether this command exited because of timeout or because cloud-init has completed. This call only adds value when the user is able to discern whether cloud-init has timed out or not, and currently in your implementation, there is no way to signal this to the caller without parsing stdout. If status is called with `--timeout 5` and the call took 5 seconds, did the call timeout or did cloud-init actually complete at 5 seconds (which is entirely possible)? Lets give the user of this new feature an example of how to use it correctly.

2024-01-03 22:13 UTC, holmanb requested changes

2024-01-31 00:20 UTC, closed without merging