handle error when log file is empty
canonical/cloud-init pull request #4859
Opened 2024-02-07 17:52 UTC by AliyevH

## Proposed Commit Message

```
<type>(optional scope): <summary>  # no more than 72 characters

A description of what the change being made is and why it is being
made if the summary line is insufficient.  This should be wrapped at
72 characters.

If you need to write multiple paragraphs, feel free.

Fixes GH-4686 (GitHub Issue number. Remove line if irrelevant)
LP: #NNNNNN (Launchpad bug number. Remove line if irrelevant)
```

## Additional Context

## Test Steps

## Checklist

- [ ] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/index.html)
- [ ] I have updated or added any [unit tests](https://cloudinit.readthedocs.io/en/latest/development/testing.html) accordingly
- [ ] I have updated or added any [documentation](https://cloudinit.readthedocs.io/en/latest/development/contribute_docs.html) accordingly

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

2024-02-08 19:03 UTC, AliyevH commented
@a-dubs Already signed CLA several times. Don't know why it does not work :)
Added username and proposed commit message.
Thanks!

2024-02-08 20:07 UTC, a-dubs commented
### Adding this to make linking back to issue easy
Fixes: 4686

2024-02-09 21:03 UTC, TheRealFalcon reviewed
@AliyevH , thanks for the contribution. While this does solve the problem, adding a `sys.exit()` into what is essentially a helper function several calls deep isn't ideal. It doesn't allow for any recovery for any other caller that might call the function.

Instead, can we raise a custom exception here (something like `EmptyFileException`), and then catch that exception at the bottom of `cloudinit/analyze/__init__.py` and print the proper text there?

2024-02-11 22:28 UTC, AliyevH commented
@TheRealFalcon Thanks for review!
1. sys exit is called in `load_events_infile` function.
2. It has been called several times only in `show.py`
3. If file is empty i think it does not make sense to continue.
4. `cloudinit/analyze/__init__.py` here we can not catch exception, because this file is not called directly. 
`if __name__ == "__main__":`
(sorry, maybe i am wrong. Trying to understand architecture. )

2024-02-12 16:36 UTC, TheRealFalcon requested changes
> cloudinit/analyze/__init__.py here we can not catch exception, because this file is not called directly.

Sorry about that. You're right. It's actually called from `main.py`. 

I still don't love having a `sys.exit(1)` here, but doing it a different way would require some more substantial refactors which isn't fair to ask for in this PR. It is ok as-as.

I left one inline comment and can we also get a test? Since we don't already have a unit test file for `cloud-init analyze show`, you can create one at `tests/unittests/analyze/test_show.py`. It should look something like

```python
from collections import namedtuple

import pytest

from cloudinit.analyze import analyze_show


@pytest.fixture
def mock_io(tmp_path):
    """Mock args for configure_io function"""
    infile = tmp_path / "infile"
    outfile = tmp_path / "outfile"
    return namedtuple("MockIO", ["infile", "outfile"])(infile, outfile)


class TestAnalyzeShow:
    """Test analyze_show (and/or helpers) in cloudinit/analyze/__init__.py"""

    def test_empty_logfile(self, mock_io, capsys):
        """Test analyze_show with an empty logfile"""
        mock_io.infile.write_text("")
        with pytest.raises(SystemExit):
            analyze_show("dontcare", mock_io)
        assert capsys.readouterr().err == f"Empty file {mock_io.infile}\n"

```

2024-02-12 16:36 UTC, TheRealFalcon commented on cloudinit/analyze/show.py
> +    if not data:
Can we add a `.strip()` here?

2024-02-12 17:22 UTC, AliyevH commented on cloudinit/analyze/show.py
> +    if not data:
Sure. I will add strip test.

2024-02-13 15:33 UTC, TheRealFalcon approved these changes
LGTM! Thanks for the contribution.

2024-02-13 15:34 UTC, merged

2024-02-13 15:43 UTC, AliyevH commented
Thank you for guiding me !