cc_growpart.py: fix handling of /dev/mapper devices for Alpine
canonical/cloud-init pull request #4876
Opened 2024-02-13 21:02 UTC by dermotbradley

## Proposed Commit Message

```
feat(Alpine) cc_growpart.py: fix handling of /dev/mapper devices for Alpine

Unlike the majority of other Linux distros /dev/mapper entries in
Alpine Linux are NOT symlinks to /dev/dm-X block devices but rather are
actual block devices themselves. This is a side-effect of Alpine's use
of mdev, rather than udev, in its initramfs.

Therefore this change works out the corresponding /dev/dm-X for any
/dev/mapper/XYZ device on Alpine.
```

## Additional Context

## Test Steps

## Checklist

- [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/index.html)
- [x] I have updated or added any [unit tests](https://cloudinit.readthedocs.io/en/latest/development/testing.html) accordingly
- [x] I have updated or added any [documentation](https://cloudinit.readthedocs.io/en/latest/development/contribute_docs.html) accordingly

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

2024-02-15 16:20 UTC, holmanb requested changes
Thanks for putting this together @dermotbradley!

I have one minor change request for using deventry.path rather than manually creating that value using deventry.name.

2024-02-15 16:21 UTC, holmanb commented
@dermotbradley This change reveals that the previous codepath assumed linux / gnu / systemd. For a better abstraction, `get_mapped_device()` probably deserves to be a static method on our Distro base class with your changes in distros/alpine.py, but I see that we have some freebsd-specific code in this module that should also make this transition so I'm happy to refactor both this and the FreeBSD code in a followup PR if you'd rather not do that in this PR - just let me know which you'd prefer.

2024-02-16 15:16 UTC, dermotbradley commented on cloudinit/config/cc_growpart.py
> +                        fulldevname = "/dev/" + deventry.name
Ok, changed now.

2024-02-16 15:18 UTC, dermotbradley commented on cloudinit/config/cc_growpart.py
> +def get_mapped_device(blockdev, distro_name):
As you mentioned below refactoring this in a separate PR along with the FreeBSD-related stuff would make sense.

2024-02-20 08:57 UTC, holmanb approved these changes
LGTM, thanks @dermotbradley!

2024-02-20 08:57 UTC, merged