fix(cc_resize): Don't warn if zpool command not found
canonical/cloud-init pull request #4969
Opened 2024-02-27 20:54 UTC by holmanb

## Proposed Commit Message
```
fix(cc_resize): Don't warn if zpool command not found

Not resizing the rootfs should not cause warnings in containers. This is expected, and how cloud-init currently behaves.

Similarly, if the image doesn't include the tools to resize the rootfs in a container, cloud-init should similarly not raise warnings.

Relocate single-use helper function outside of util.py.
```

## Additional Context
many container test failures, [including this one](https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-noble-lxd_container/lastCompletedBuild/testReport/)

## Test Steps
To hit this codepath, I believe you need zfs-backed lxd storage, which I do not have. Should be reproducible via:
```
tox -e integration-tests --  tests/integration_tests/modules/test_cli.py::test_valid_userdata
```

## Checklist

- [ ] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/index.html)
- [ ] I have updated or added any [unit tests](https://cloudinit.readthedocs.io/en/latest/development/testing.html) accordingly
- [ ] I have updated or added any [documentation](https://cloudinit.readthedocs.io/en/latest/development/contribute_docs.html) accordingly

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

2024-02-27 21:42 UTC, simondeziel commented
@holmanb I just proposed #4970 hoping to fix https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/2055219 but apparently you PR covers more ground and better. Should I close mine?

2024-02-27 21:48 UTC, blackboxsw commented
> @holmanb I just proposed #4970 hoping to fix https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/2055219 but apparently your PR covers more ground and better. Should I close mine?

I think @holmanb was pulling this together based on integration-test failures he saw. 

@simondeziel thanks for the bug and the PR to followup. I think it's probably best to close your PR as Bret's going to make this warning conditonal on non-container systems

@holmanb can you also tie one of the commits in this PR to `LP: #2055219`

2024-02-27 22:08 UTC, blackboxsw requested changes
Thanks Brett and a couple nits here

2024-02-27 22:08 UTC, blackboxsw commented on cloudinit/config/cc_resizefs.py
> +        LOG.info("No zpool found: %s: %s", zpool, err)
In this case, we probably want to log zpoolstatus as well because we were unable to parse it.

2024-02-27 22:14 UTC, blackboxsw reviewed
Might we want to consolidate the logging/warning function to avoid carrying around the container variable and the conditionals since we are logging the same messages, albeit different log levels?
```diff
--- a/cloudinit/config/cc_resizefs.py
+++ b/cloudinit/config/cc_resizefs.py
@@ -150,7 +150,7 @@ RESIZE_FS_PRECHECK_CMDS = {"ufs": _can_skip_resize_ufs}
 
 def get_device_info_from_zpool(zpool) -> Optional[str]:
     # zpool has 10 second timeout waiting for /dev/zfs LP: #1760173
-    container = util.is_container()
+    log_warn = LOG.debug if util.is_container() else LOG.warn
     if not os.path.exists("/dev/zfs"):
         LOG.debug("Cannot get zpool info, no /dev/zfs")
         return None
@@ -164,12 +164,9 @@ def get_device_info_from_zpool(zpool) -> Optional[str]:
             )
             return None
     except subp.ProcessExecutionError as err:
-        if container:
-            LOG.info(
-                "Unable to get zpool status of %s: %s in container", zpool, err
-            )
-            return None
-        LOG.warning("Unable to get zpool status of %s: %s", zpool, err)
+        log_warn(
+            "Unable to get zpool status of %s: %s in container", zpool, err
+        )
         return None
     r = r".*(ONLINE).*"
     for line in zpoolstatus.split("\n"):
@@ -177,10 +174,7 @@ def get_device_info_from_zpool(zpool) -> Optional[str]:
             disk = line.split()[0]
             LOG.debug('found zpool "%s" on disk %s', zpool, disk)
             return disk
-    if container:
-        LOG.info("No zpool found: %s: %s", zpool, err)
-    else:
-        LOG.warning("No zpool found %s: %s", zpool, err)
+    log_warn("No zpool found [%s]: out: %s: err: %s", zpool, zpoolstatus, err)
     return None
```

2024-02-27 22:25 UTC, blackboxsw reviewed
Confirmed successful behavior on zfs-backed LXD containers

2024-02-27 22:33 UTC, blackboxsw commented on cloudinit/config/cc_resizefs.py
> +            LOG.info(
Also, here we are treating absence of zpool cmd in the same manner as other potential errors. This results in a slightly more 'messy' log message on containers
```
2024-02-27 22:29:24,361 - cc_resizefs.py[DEBUG]: Unable to get zpool status of tank: Unexpected error while running command.
Command: ['zpool', 'status', 'tank']
Exit code: -
Reason: [Errno 2] No such file or directory: b'zpool'
Stdout: -
Stderr: - in container
```
If we also performed a pre-flight subp.which("zpool") we could provide a more concise, `Skipping zpool status: no zpool command` which would avoid Errno in logs.

2024-02-27 22:52 UTC, holmanb commented
Great suggestions, thanks @blackboxsw. The patch was corrupted when I tried to apply it, but I think I got your requests in.

Ready for re-review.

2024-02-27 23:02 UTC, holmanb commented
> @holmanb I just proposed https://github.com/canonical/cloud-init/pull/4970 hoping to fix https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/2055219 

Thanks for the contribution bug report and PR - you were on the right track too :)

> but apparently your PR covers more ground and better. Should I close mine?

I think we're going to move forward with this PR, so yes please.

2024-02-27 23:27 UTC, blackboxsw approved these changes
LGTM! thanks!

2024-02-27 23:27 UTC, merged

2024-02-28 14:06 UTC, simondeziel commented on cloudinit/config/cc_resizefs.py
> +            LOG.info(
@holmanb maybe I missed it but Chad's suggestion of using a pre-flight check with `subp.which("zpool")` seems to be missing in the code merged.