fix: Stop attempting to resize ZFS in cc_growpart on Linux
canonical/cloud-init pull request #5370
Opened 2024-06-04 22:04 UTC by TheRealFalcon

WIP: untested

## Proposed Commit Message

```
fix: Stop attempting to resize ZFS in cc_growpart on Linux

In e520c944, growing ZFS was added to cc_growpart to support BSD
systems. However, this left Linux in a state where it will fail to
resize and log a warning anytime it encounters ZFS. This commit
ensures that the cc_growpart resize is only attempted on BSD (or any
other system that uses `growfs`). This leaves cc_resizefs to grow the
filesystem on Linux.

This is admittedly a hack solution and long term, we should ensure
that ZFS gets grown in one module, and find a better long-term
abstraction for volume managers.

```

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

2024-06-04 22:05 UTC, TheRealFalcon commented on cloudinit/config/cc_growpart.py
> +def resizer_factory(mode: str, distro: Distro, devices: list) -> Resizer:
This entire function was moved as-is so to be able to reference the `Resizer` return type

2024-06-05 00:39 UTC, holmanb reviewed
I haven't tested this, but the approach looks good for now.

I agree that it's not ideal to have resize happening in different places on different OSes. I do think that growpart is a slightly more natural fit ZFS resizing, but we can bikeshed that another day.

2024-06-05 03:53 UTC, blackboxsw requested changes
This looks good for the time being. It retains BSD support for growfs which is what was intended and doesn't degrade the current skip behavior on all non-BSD/non-growfs environments.

We need to change that early return to a continue. But beyond that +1.


Also we need to fix the resizer class `myresizer` in the following test to subclass from  ResizeGrowFS 
 to avoid failing the unit test now. tests/unittests/config/test_cc_growpart.py::TestResizeZFS::test_zroot[zroot/ROOT/nochange-NOCHANGE]

2024-06-05 03:53 UTC, blackboxsw commented on cloudinit/config/cc_growpart.py
>              return info
This should be a continue, not a return in case there are other devices listed in `growpart: devices: [..]`
```suggestion
            continue
```

2024-06-05 13:45 UTC, TheRealFalcon commented
Addressed comment from @blackboxsw , updated tests, and manually verified that ZFS systems (both from containers and a mounted disk in a VM) result in no log warnings. Ready for review.

2024-06-05 16:29 UTC, blackboxsw approved these changes
Content and behavior look good for this PR. Thanks @TheRealFalcon

2024-06-05 16:55 UTC, merged