Update behavior of base bond interface with NetworkManager
canonical/cloud-init pull request #5385
Opened 2024-06-06 19:50 UTC by jcmoore3

When using NetworkManager, if the base bond interface does not have subnet information configured, ensure it is disabled with respect to ipv4 and ipv6. Otherwise, the base bond interface defaults to 'auto' and will try to configure itself via DHCP. This is problematic when using a tagged VLAN interface on top of the bond as the base interface will try to configure itself via DHCP on the untagged VLAN.

## Proposed Commit Message

```
fix: Update behavior of base bond interface with NetworkManager

When using NetworkManager, if the base bond interface does not have
subnet information configured, ensure it is disabled with respect to
ipv4 and ipv6. Otherwise, the base bond interface defaults to 'auto'
and will try to configure itself via DHCP. This is problematic when
using a tagged VLAN interface on top of the bond as the base
interface will try to configure itself via DHCP on the untagged VLAN.

```

## Additional Context

## Test Steps

## Checklist

- [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/index.html)
- [ ] I have updated or added any [unit tests](https://cloudinit.readthedocs.io/en/latest/development/testing.html) accordingly
- [ ] I have updated or added any [documentation](https://cloudinit.readthedocs.io/en/latest/development/contribute_docs.html) accordingly

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

2024-06-25 12:50 UTC, jcmoore3 commented
Apologies that the CLA is taking so long. This needs to go through my company's internal open source approval process. I do not anticipate any issues, it just takes time. I'm hoping to have final internal approval this week.

2024-06-27 16:00 UTC, jcmoore3 commented
CLA signed, please let me know if anything else is required to get this moving. Change to github-cla-signers is in PR #5369.

2024-06-28 11:23 UTC, aciba90 requested changes
Thanks, @jcmoore3, for fixing this. The changes look good to me, but unit tests need to be adapted and the new paths need to be covered.

2024-07-10 17:01 UTC, jcmoore3 commented
@aciba90 I have updated the unit tests but please note that there is a dependency on the change in #5496. Without this change, cloud-init current configures DNS settings for disabled interfaces which disallows NetworkManager from activating the interface.

2024-07-11 10:07 UTC, aciba90 requested changes
Thanks for adding unit-tests! The problem you are describing happens if:

1. Base bond interface without ipvX.method defined defaulted to `auto`
2. VLAN linked interfaces with ipvX.method set to `manual`

Your PR proposes to change the default from `auto` to `disabled` for every interface without subnets. I have in-line requested to limit it, even more, to "bond" only interfaces.

In order to assess whether this fix should be backported or not, I am trying to think if cloud-init changes behavior with this change, as, for the described cases, we are fixing a bug, but for other cases, we are changing the default and possibly breaking other use-cases.

2024-07-12 15:29 UTC, aciba90 requested changes
Thanks for limiting the change to bond interfaces. After that, the changed unittests are not relevant because they are xkipped, so could you please remove them applying the following patch:

<details>
  <summary>remove-tests.patch</summary>
 
  ```patch
commit 976707b7ca6d53b920cc2d82418f719b5e3f4da6
Author: Alberto Contreras <alberto.contreras@canonical.com>
Date:   Fri Jul 12 15:17:32 2024 +0200

    revert not needed tests changes
    
    line changes
    tests that are marked as xfail

diff --git a/tests/unittests/net/artifacts/no_matching_mac/etc/NetworkManager/system-connections/cloud-init-encc000.nmconnection b/tests/unittests/net/artifacts/no_matching_mac/etc/NetworkManager/system-connections/cloud-init-encc000.nmconnection
index 57222589f..fbdfbc652 100644
--- a/tests/unittests/net/artifacts/no_matching_mac/etc/NetworkManager/system-connections/cloud-init-encc000.nmconnection
+++ b/tests/unittests/net/artifacts/no_matching_mac/etc/NetworkManager/system-connections/cloud-init-encc000.nmconnection
@@ -11,4 +11,3 @@ interface-name=encc000
 org.freedesktop.NetworkManager.origin=cloud-init
 
 [ethernet]
-
diff --git a/tests/unittests/net/network_configs.py b/tests/unittests/net/network_configs.py
index 80c36dd0b..b68319cc8 100644
--- a/tests/unittests/net/network_configs.py
+++ b/tests/unittests/net/network_configs.py
@@ -1943,14 +1943,6 @@ pre-down route del -net 10.0.0.0/8 gw 11.0.0.1 metric 3 || true
                 [ethernet]
                 mac-address=66:BB:9F:2C:E8:80
 
-                [ipv4]
-                method=disabled
-                may-fail=false
-
-                [ipv6]
-                method=disabled
-                may-fail=false
-
                 """
             ),
             "cloud-init-eth5.nmconnection": textwrap.dedent(
@@ -2066,14 +2058,6 @@ pre-down route del -net 10.0.0.0/8 gw 11.0.0.1 metric 3 || true
                 [ethernet]
                 mac-address=98:BB:9F:2C:E8:80
 
-                [ipv4]
-                method=disabled
-                may-fail=false
-
-                [ipv6]
-                method=disabled
-                may-fail=false
-
                 """
             ),
             "cloud-init-eth1.nmconnection": textwrap.dedent(
@@ -2094,14 +2078,6 @@ pre-down route del -net 10.0.0.0/8 gw 11.0.0.1 metric 3 || true
                 [ethernet]
                 mac-address=AA:D6:9F:2C:E8:80
 
-                [ipv4]
-                method=disabled
-                may-fail=false
-
-                [ipv6]
-                method=disabled
-                may-fail=false
-
                 """
             ),
             "cloud-init-br0.nmconnection": textwrap.dedent(
@@ -2709,14 +2685,6 @@ pre-down route del -net 10.0.0.0/8 gw 11.0.0.1 metric 3 || true
                 [ethernet]
                 mac-address=66:BB:9F:2C:E8:80
 
-                [ipv4]
-                method=disabled
-                may-fail=false
-
-                [ipv6]
-                method=disabled
-                may-fail=false
-
                 """
             ),
             "cloud-init-eth5.nmconnection": textwrap.dedent(
@@ -3710,14 +3678,6 @@ iface bond0 inet6 static
                 [ethernet]
                 mac-address=AA:BB:CC:DD:E8:00
 
-                [ipv4]
-                method=disabled
-                may-fail=false
-
-                [ipv6]
-                method=disabled
-                may-fail=false
-
                 """
             ),
             "cloud-init-bond0s1.nmconnection": textwrap.dedent(
@@ -3738,14 +3698,6 @@ iface bond0 inet6 static
                 [ethernet]
                 mac-address=AA:BB:CC:DD:E8:01
 
-                [ipv4]
-                method=disabled
-                may-fail=false
-
-                [ipv6]
-                method=disabled
-                may-fail=false
-
                 """
             ),
             "cloud-init-bond0.nmconnection": textwrap.dedent(
  ```
</details>

As this PR depends on https://github.com/canonical/cloud-init/pull/5496, and that one will add unit tests, let's wait until 5496 is merged and add the tests after a rebase.

2024-07-15 13:22 UTC, jcmoore3 commented
@aciba90 The tests have been updated as suggested

2024-07-18 06:07 UTC, aciba90 requested changes
Could you please rebase main to include https://github.com/canonical/cloud-init/pull/5496 and include unit tests covering this change ?

2024-07-18 06:07 UTC, aciba90 commented on tests/unittests/net/artifacts/no_matching_mac/etc/NetworkManager/system-connections/cloud-init-encc000.nmconnection
> +
This extra line is unneeded, could please remove it?

2024-07-23 10:02 UTC, aciba90 requested changes
Thanks for rebasing `main` and adapting the existent tests. Could you please include unit tests covering this change?

2024-08-14 08:29 UTC, aciba90 approved these changes
LGTM, I see now that the unit tests cover the change, no need to add extra ones. Thanks!

2024-08-14 08:29 UTC, merged