tests: canonical-kernel devel series unavailable in daily ppa
canonical/cloud-init pull request #5450
Opened 2024-06-25 23:06 UTC by blackboxsw

## Proposed Commit Message
```
tests: canonical-kernel devel series unavailable in daily ppa

Expect specific error on devel series for canonical-kernel PPA.
Add IS_UBUNTU_DEVEL conditional to releases to allow cloud-init
to ignore a specific error about missing Release file on
devel series in the future.
```

## Additional Context

The canonical-kernel-team PPA doesn't currently publish oracular series packages as it is a development release. 
https://launchpad.net/~canonical-kernel-team/+archive/ubuntu/ppa

Given that oracular/devel builds may trail the opening of a devel release for a bit, add optional ignore_errors on missing canonical-kernel due to a missing Release file (indicating no packages published and/or signed for this series yet).

## Test Steps
```
CLOUD_INIT_OS_IMAGE=noble CLOUD_INIT_CLOUD_INIT_SOURCE=IN_PLACE tox -e integration-tests -- tests/integration_tests/modules/test_apt_functionality.py::test_install_missing_deps

CLOUD_INIT_OS_IMAGE=oracular CLOUD_INIT_CLOUD_INIT_SOURCE=IN_PLACE tox -e integration-tests -- tests/integration_tests/modules/test_apt_functionality.py::test_install_missing_deps
````

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

2024-06-26 23:39 UTC, holmanb requested changes
test fails for me (`CLOUD_INIT_OS_IMAGE=oracular CLOUD_INIT_CLOUD_INIT_SOURCE=IN_PLACE tox -e integration-tests -- tests/integration_tests/modules/test_apt_functionality.py::test_install_missing_deps`)
```
FAILED tests/integration_tests/modules/test_apt_functionality.py::test_install_missing_deps - AssertionError: Found unexpected errors: ERROR]: Failed to update package using apt: Unexpected error while running command.
========================== 1 failed, 3 warnings in 114.80s (0:01:54) ===========================
integration-tests: exit 1 (116.37 seconds) /home/holmanb/ci-b> .tox/integration-tests/bin/python -m pytest -vv --log-cli-level=INFO --durations 10 tests/integration_tests/modules/test_apt_functionality.py::test_install_missing_deps pid=2779270
  integration-tests: FAIL code 1 (180.18=setup[63.82]+cmd[116.37] seconds)
  evaluation failed :( (180.30 seconds)
```

2024-06-27 03:11 UTC, blackboxsw commented
> test fails for me (`CLOUD_INIT_OS_IMAGE=oracular CLOUD_INIT_CLOUD_INIT_SOURCE=IN_PLACE tox -e integration-tests -- tests/integration_tests/modules/test_apt_functionality.py::test_install_missing_deps`)
> 
> ```
> FAILED tests/integration_tests/modules/test_apt_functionality.py::test_install_missing_deps - AssertionError: Found unexpected errors: ERROR]: Failed to update package using apt: Unexpected error while running command.
> ========================== 1 failed, 3 warnings in 114.80s (0:01:54) ===========================
> integration-tests: exit 1 (116.37 seconds) /home/holmanb/ci-b> .tox/integration-tests/bin/python -m pytest -vv --log-cli-level=INFO --durations 10 tests/integration_tests/modules/test_apt_functionality.py::test_install_missing_deps pid=2779270
>   integration-tests: FAIL code 1 (180.18=setup[63.82]+cmd[116.37] seconds)
>   evaluation failed :( (180.30 seconds)
> ```

Strange as I'm seeing successes on both noble and oracular for lxd_container
```
csmith@midtown:~/src/cloud-init$ CLOUD_INIT_OS_IMAGE=noble CLOUD_INIT_CLOUD_INIT_SOURCE=IN_PLACE tox -e integration-tests -- tests/integration_tests/modules/test_apt_functionality.py::test_install_missing_deps
integration-tests: commands[0]> .tox/integration-tests/bin/python -m pytest -vv --log-cli-level=INFO --durations 10 tests/integration_tests/modules/test_apt_functionality.py::test_install_missing_deps
============================= test session starts ==============================
platform linux -- Python 3.11.6, pytest-8.2.2, pluggy-1.5.0 -- /home/csmith/src/cloud-init/.tox/integration-tests/bin/python
cachedir: .tox/integration-tests/.pytest_cache
rootdir: /home/csmith/src/cloud-init
configfile: tox.ini
collected 1 item                                                               

tests/integration_tests/modules/test_apt_functionality.py::test_install_missing_deps 
-------------------------------- live log setup --------------------------------
2024-06-26 21:07:47 INFO      integration_testing:clouds.py:76 Settings:
CLOUD_INIT_SOURCE=IN_PLACE
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
INCLUDE_COVERAGE=False
INCLUDE_PROFILE=False
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OS_IMAGE=noble
PLATFORM=lxd_container
RUN_UNSTABLE=False
-------------------------------- live log call ---------------------------------
2024-06-26 21:07:47 INFO      integration_testing:clouds.py:143 Launching instance with launch_kwargs:
image_id=ubuntu-daily:91c12543d4f638d7696684d12e2123938c41165711947cc7200e1eb0cb0fa55c
user_data=
#cloud-config
runcmd:
  - DEBIAN_FRONTEND=noninteractive apt-get remove gpg -y

username=ubuntu
2024-06-26 21:07:49 INFO      pycloudlib.cloud.LXDContainer:cloud.py:253 ['lxc', 'init', 'ubuntu-daily:91c12543d4f638d7696684d12e2123938c41165711947cc7200e1eb0cb0fa55c', 'cloudinit-0627-030747uh72drtw', '--config', 'user.meta-data=public-keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDKvT/O9ipXmPXQz4SeLiZEunwMdsGfXQItHfkTrg/IwPy6wr7QCUkHU+2cnXbFtQPcUTV2hbby/eZUBHLR1U6E0ca4kv16mVg8xXp1gphRzYj7CsvZ29S+G51HAYS33BU/78qNY3lgLIUiRk/EviFTprVmW8/cNkfBi1Du4GvNUEGiRTAI8zt7cCYEji3+3mCu/dIAo5kHyJxdn986K2LhhcD1VCzrX8PPpEIsO2uhm29Aw01hs6ZvEYCdpMVmVLG3Po19XkHrD6gFtViuB+0x1sdBmXxXTHiWof39DXgSy0JRjbXNHpcHrHtBZ+/wLSXVG7oehFh9ZB697Ugq3vckoVWouwg7RklcdtHmFmauC/HXQgvR8uOanJ6aARBYvXMjBA+mbC2LC9ERncQIqAKjSiWmUOq6DdbBzzQ8Azg36gcbwJx2U7rYbTKW4o0nUd5asDfG1gZblGadzqrPfIudQ/SLVjUpH0ntD9Jhz2/0tzVs0ZbrnRzQs4WN+iGCPn0= csmith@uptown\n', '--config', 'user.user-data=\n#cloud-config\nruncmd:\n  - DEBIAN_FRONTEND=noninteractive apt-get remove gpg -y\n']
2024-06-26 21:08:19 INFO      integration_testing:clouds.py:307 Mounting source /home/csmith/src/cloud-init/cloudinit directly onto LXD container/VM named cloudinit-0627-030747uh72drtw at /usr/lib/python3/dist-packages/cloudinit
2024-06-26 21:08:19 INFO      integration_testing:clouds.py:307 Mounting source /home/csmith/src/cloud-init/templates directly onto LXD container/VM named cloudinit-0627-030747uh72drtw at /etc/cloud/templates
2024-06-26 21:08:20 INFO      integration_testing:clouds.py:307 Mounting source /home/csmith/src/cloud-init/doc/module-docs directly onto LXD container/VM named cloudinit-0627-030747uh72drtw at /usr/share/doc/cloud-init/module-docs
2024-06-26 21:08:21 INFO      pycloudlib.instance:instance.py:494 _wait_for_execute to complete
2024-06-26 21:08:24 INFO      paramiko.transport:transport.py:1909 Connected (version 2.0, client OpenSSH_9.6p1)
2024-06-26 21:08:24 INFO      paramiko.transport:transport.py:1909 Authentication (publickey) successful!
2024-06-26 21:08:25 INFO      pycloudlib.instance:instance.py:515 _wait_for_cloudinit to complete
2024-06-26 21:08:25 INFO      pycloudlib.instance:instance.py:270 executing: sh -c 'command -v systemctl'
2024-06-26 21:08:31 INFO      pycloudlib.instance:instance.py:270 executing: cloud-init status --wait --long
2024-06-26 21:08:31 INFO      integration_testing:clouds.py:154 Launched instance: LXDInstance(name=cloudinit-0627-030747uh72drtw)
2024-06-26 21:08:31 INFO      pycloudlib.instance:instance.py:270 executing: sudo -- sh -c 'cloud-init --version'
2024-06-26 21:08:31 INFO      integration_testing:clouds.py:158 cloud-init version: /usr/bin/cloud-init 24.1.7
2024-06-26 21:08:31 INFO      pycloudlib.instance:instance.py:270 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
2024-06-26 21:08:31 INFO      integration_testing:clouds.py:164 image serial: 20240622
2024-06-26 21:08:31 INFO      pycloudlib.instance:instance.py:270 executing: sh -c 'sudo cloud-init clean --logs'
2024-06-26 21:08:32 INFO      pycloudlib.instance:instance.py:270 executing: sh -c 'sudo echo '"'"'uninitialized'"'"' > /etc/machine-id'
2024-06-26 21:08:32 INFO      pycloudlib.instance:instance.py:270 executing: sh -c 'sudo rm -rf /var/log/syslog'
2024-06-26 21:08:32 INFO      pycloudlib.instance:instance.py:270 executing: sh -c 'sudo cloud-init clean --logs'
2024-06-26 21:08:32 INFO      pycloudlib.instance:instance.py:270 executing: sh -c 'sudo echo '"'"'uninitialized'"'"' > /etc/machine-id'
2024-06-26 21:08:32 INFO      pycloudlib.instance:instance.py:270 executing: sh -c 'sudo rm -rf /var/log/syslog'
2024-06-26 21:09:03 INFO      integration_testing:instances.py:141 Created new image: local:cloudinit-0627-030747uh72drtw-snapshot
2024-06-26 21:09:04 INFO      integration_testing:clouds.py:143 Launching instance with launch_kwargs:
image_id=local:cloudinit-0627-030747uh72drtw-snapshot
user_data=#cloud-config
apt:
  sources:
    test_keyserver:
      keyid: 1BC30F715A3B861247A81A5E55FE7C8C0165013E
      keyserver: keyserver.ubuntu.com
      # Hard-code noble as devel releases may not see new packages for some time
      source: "deb http://ppa.launchpad.net/curtin-dev/daily/ubuntu noble main"
    test_ppa:
      keyid: 441614D8
      keyserver: keyserver.ubuntu.com
      source: "ppa:simplestreams-dev/trunk"

username=ubuntu
2024-06-26 21:09:04 INFO      pycloudlib.cloud.LXDContainer:cloud.py:253 ['lxc', 'init', 'local:cloudinit-0627-030747uh72drtw-snapshot', 'cloudinit-0627-030904u5gu9qxg', '--config', 'user.meta-data=public-keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDKvT/O9ipXmPXQz4SeLiZEunwMdsGfXQItHfkTrg/IwPy6wr7QCUkHU+2cnXbFtQPcUTV2hbby/eZUBHLR1U6E0ca4kv16mVg8xXp1gphRzYj7CsvZ29S+G51HAYS33BU/78qNY3lgLIUiRk/EviFTprVmW8/cNkfBi1Du4GvNUEGiRTAI8zt7cCYEji3+3mCu/dIAo5kHyJxdn986K2LhhcD1VCzrX8PPpEIsO2uhm29Aw01hs6ZvEYCdpMVmVLG3Po19XkHrD6gFtViuB+0x1sdBmXxXTHiWof39DXgSy0JRjbXNHpcHrHtBZ+/wLSXVG7oehFh9ZB697Ugq3vckoVWouwg7RklcdtHmFmauC/HXQgvR8uOanJ6aARBYvXMjBA+mbC2LC9ERncQIqAKjSiWmUOq6DdbBzzQ8Azg36gcbwJx2U7rYbTKW4o0nUd5asDfG1gZblGadzqrPfIudQ/SLVjUpH0ntD9Jhz2/0tzVs0ZbrnRzQs4WN+iGCPn0= csmith@uptown\n', '--config', 'user.user-data=#cloud-config\napt:\n  sources:\n    test_keyserver:\n      keyid: 1BC30F715A3B861247A81A5E55FE7C8C0165013E\n      keyserver: keyserver.ubuntu.com\n      # Hard-code noble as devel releases may not see new packages for some time\n      source: "deb [...]

2024-06-27 11:58 UTC, holmanb approved these changes
@blackboxsw LGTM

2024-06-27 11:59 UTC, holmanb commented
> > test fails for me (`CLOUD_INIT_OS_IMAGE=oracular CLOUD_INIT_CLOUD_INIT_SOURCE=IN_PLACE tox -e integration-tests -- tests/integration_tests/modules/test_apt_functionality.py::test_install_missing_deps`)
> > ```
> > FAILED tests/integration_tests/modules/test_apt_functionality.py::test_install_missing_deps - AssertionError: Found unexpected errors: ERROR]: Failed to update package using apt: Unexpected error while running command.
> > ========================== 1 failed, 3 warnings in 114.80s (0:01:54) ===========================
> > integration-tests: exit 1 (116.37 seconds) /home/holmanb/ci-b> .tox/integration-tests/bin/python -m pytest -vv --log-cli-level=INFO --durations 10 tests/integration_tests/modules/test_apt_functionality.py::test_install_missing_deps pid=2779270
> >   integration-tests: FAIL code 1 (180.18=setup[63.82]+cmd[116.37] seconds)
> >   evaluation failed :( (180.30 seconds)
> > ```
> 
> Strange as I'm seeing successes on both noble and oracular for lxd_container


Just reran and it passed, nevermind.

2024-06-27 12:44 UTC, merged