doc: Update docs on boothooks
canonical/cloud-init pull request #5541
Opened 2024-07-24 13:45 UTC by aciba90

## Proposed Commit Message

```
doc: Update docs on boothooks

Improve explaination on #cloud-boothook for end-users.

Reorder and improve doc/rtd/explanation/format.rst.

SC-1657
Fixes GH-4542

Co-authored-by: Calvin Mwadime <calvin.mwadime@canonical.com>
```

## Additional Context

This PR builds-up on top of https://github.com/canonical/cloud-init/pull/4650.

## Test Steps

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

2024-07-24 14:16 UTC, TheRealFalcon reviewed
Hmmm...I'm currently overhauling the user formats page per https://github.com/canonical/cloud-init/issues/4739 and a separate entry in our spreadsheet.

Is there any way we can just capture the new info here but remove any of the non-boothook related changes or formatting changes?

2024-07-24 17:41 UTC, a-dubs requested changes
Thanks for all your work on this @aciba90!! I left a few inline questions, comments, and suggestions.

2024-07-24 17:41 UTC, a-dubs commented on doc/rtd/explanation/format.rst
> +an error occurs reading a file the remaining files will not be read.
what is meant by "set of rules". and why is it the same for all urls? This might need re-written for dummies like me :P

2024-07-24 17:41 UTC, a-dubs commented on doc/rtd/explanation/format.rst
> +potentially on every boot, with less convenience as ``cc_bootcmd`` but more
```suggestion
potentially on every boot, with less convenience than ``cc_bootcmd``, but more
```

2024-07-24 17:41 UTC, a-dubs commented on doc/rtd/explanation/format.rst
> +   Boothooks are execute on every boot.
```suggestion
   Boothooks are executed on every boot.
```

2024-07-24 17:41 UTC, a-dubs commented on doc/rtd/explanation/format.rst
> +   functionality.
maybe add a final little sentence saying as demonstrated below in [link to "Example of once-per-instance script" section]

2024-07-24 17:41 UTC, a-dubs commented on doc/rtd/explanation/format.rst
> +User data format to Mime Content type mapping
should "Mime Content" be lowercase?

2024-07-24 17:41 UTC, a-dubs commented on doc/rtd/explanation/format.rst
> +
I think i might just be dense or have overlooked something, but I am unsure of what to do with this information now. 

Where do I put `Content-Type: text/<content-type>`? I just don't know how or where this is used. "content-type" doesn't seem to appear really anywhere else in these docs.

2024-07-24 17:41 UTC, a-dubs commented on doc/rtd/explanation/format.rst
> +Below is a mapping of a specific user data format to the `content-type`
Not sure if this in an improvement but still i feel like this sentence is a little bit confusing.
```suggestion
Below is a mapping of each specific user data format to the `content-type`
```

2024-07-24 20:43 UTC, rpocase commented on doc/rtd/explanation/format.rst
> +User data format to Mime Content type mapping
or maybe "MIME content"

2024-07-25 08:26 UTC, aciba90 commented
> Hmmm...I'm currently overhauling the user formats page per #4739 and a separate entry in our spreadsheet.
> 
> Is there any way we can just capture the new info here but remove any of the non-boothook related changes or formatting changes?

I have created https://github.com/canonical/cloud-init/pull/5546 with only changes related to boothook, please feel free to merge, [integrate it in your PR](https://patch-diff.githubusercontent.com/raw/canonical/cloud-init/pull/5546.patch) or whatever, thanks!

Closing this one.

2024-07-25 08:26 UTC, closed without merging