azure: add PPS support for azure-proxy-agent
canonical/cloud-init pull request #5601
Opened 2024-08-09 19:20 UTC by KsenijaS

## Proposed Commit Message

```
feat(azure): add PPS support for azure-proxy-agent

This PR adds PPS support for azure-proxy agent and improves error logging.

```

## Additional Context

## Test Steps

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

2024-08-09 19:28 UTC, cjp256 approved these changes
LGTM, thanks!  I think @blackboxsw will like the new logs :D Unit tests need updating though.

2024-08-15 04:34 UTC, blackboxsw requested changes
Thanks @KsenijaS for this PR and the improved logs are appreciated. Is there an existing unit test or new unit test we can extend that asserts we check azure proxy agent status in PPS when config is properly set? Then we can ensure we don't degrade this expected behavior in the future.

2024-08-15 04:34 UTC, blackboxsw commented on cloudinit/sources/DataSourceAzure.py
> +                self._check_azure_proxy_agent_status()
No unittests cover this new PPS invocation. If possible can we extend tests/unittests/sources/test_azure::...test_*_pps tests with `construct_ovf_env(provision_guest_proxy_agent=True)` to ensure we get into _check_azure_proxy_agent_status.

2024-08-16 13:33 UTC, cjp256 commented on tests/unittests/sources/test_azure.py
> +        assert self.mock_subp_subp.mock_calls == [
Awesome, thanks for adding the tests!

For the non-gpa PPS case(s), can we add the counterpoint case (`assert self.mock_subp_subp.mock_calls == []`)?

2024-08-16 16:39 UTC, cjp256 approved these changes
LGTM, thanks for the tests!

2024-08-23 18:15 UTC, KsenijaS commented
LGTM! :)

2024-08-27 13:35 UTC, blackboxsw approved these changes
And also LGTM,  Thank you for getting that exhaustive test coverage here.

2024-08-27 13:36 UTC, merged