fix: avoid deprecation level logs for cli stags when providing --file
canonical/cloud-init pull request #5770
Opened 2024-10-02 18:23 UTC by blackboxsw

## Proposed Commit Message

```
fix: avoid deprecation level logs for cli stags when providing --file

Avoid raising deprecations command line calls to cloud-init boot
stages when the optional --file param is also provided.

When cloud-init's boot stages are invoked with a --file argument
this is typically an attempt to add suppplemental configuration to a
system after initial boot has completed.

Although direct calls to cloud-init boot stages could lead to
misconfiguration if boot stages are called out of sequence
of customized /etc/cloud/cloud.cfg altering which config modules are
run during the boot stage, the support of such environments is out of
scope for this feature. It remains a simple tool to apply additional
configuration via user-data onto an existing system after initial boot.

At some point in the future, a new sub-command may be provided by
cloud-init tooling to allow for supplemental configuration of user-data
post-boot, in that event this --file feature will become deprecated in
favor of a cleaner/simpler alternative.

Fixes GH-5726
```

## Additional Context
This fix will be backported to Ubuntu Oracular as a bug fix as well, avoiding exit 2 from cloud-init status and DEPRECATION or INFO level logs for users or tooling which call cloud-init boot stages with the `--file` param.

## Test Steps
```
CLOUD_INIT_OS_IMAGE=oracular CLOUD_INIT_CLOUD_INIT_SOURCE=IN_PLACE tox -e integration-tests -- tests/integration_tests/cmd/test_stages.py

# Test stable series non-deprecation level logs by modifying cloudint/features.py locally before running against focal
sed -i 's/devel/22.1/' cloudinit/features.py 
CLOUD_INIT_OS_IMAGE=focal CLOUD_INIT_CLOUD_INIT_SOURCE=IN_PLACE tox -e integration-tests -- tests/integration_tests/cmd/test_stages.py
```

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

2024-10-02 19:56 UTC, TheRealFalcon reviewed
We should also remove the deprecated text in our CLI output at https://github.com/canonical/cloud-init/blob/main/cloudinit/cmd/main.py#L991 and later

2024-10-02 20:06 UTC, holmanb requested changes
This approach leaves those that are calling these stages manually without `--files` in a deprecated state still. Why would we want to deprecate for only non-`--files` callers?

2024-10-02 20:45 UTC, TheRealFalcon approved these changes
LGTM!

2024-10-03 22:43 UTC, holmanb approved these changes

2024-10-04 18:41 UTC, merged