ubuntu/noble: Fix bad refresh of no-single-process.patch in 04fc0d8
canonical/cloud-init pull request #5880
Opened 2024-11-15 21:59 UTC by TheRealFalcon

2024-11-16 00:10 UTC, holmanb approved these changes
This fixes the issues that I see. Thanks!

2024-11-16 00:55 UTC, holmanb requested changes
Actually, this is going into the file `no-nocloud-network.patch` - that doesn't seem right.

2024-11-16 03:14 UTC, TheRealFalcon commented
🤦‍♂️, good find!

2024-11-18 17:59 UTC, holmanb approved these changes

2024-11-18 18:19 UTC, merged