fix: uninstall custom signal handlers before shutdown
canonical/cloud-init pull request #5913
Opened 2024-12-05 23:44 UTC by holmanb

## Proposed Commit Message

```
fix: uninstall custom signal handlers before shutdown

Fixes GH-5849
Fixes LP: 2089185
```

## Additional Context

This might address the following bug reports:

https://bugs.launchpad.net/maas/+bug/2089185
https://github.com/canonical/cloud-init/issues/5849

## Test Steps

I haven't been able to reproduce either bug, so testing is needed.

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

2024-12-10 20:10 UTC, TheRealFalcon commented
@holmanb , I'm assuming we're looking for some confirmation that this approach works before reviewing?

2024-12-17 13:19 UTC, r00ta commented
We tested this patch but it does not work. As per chat ee decided to release a [fix](https://code.launchpad.net/~r00ta/maas/+git/maas/+merge/478384) in MAAS directly.

So, if this patch was supposed to be used only for MAAS we can close it. Thanks!

2025-01-07 19:04 UTC, holmanb commented on tests/integration_tests/modules/test_power_state_change.py
> +            ("halt", "+1", "0", re.escape("will execute: shutdown -H +1 msg")),
Did this ever pass?

Perhaps something changed in the verify ordering utility.

2025-01-07 19:09 UTC, holmanb commented on cloudinit/signal_handler.py
> +def inspect_handler(sig: Union[int, Callable, None]) -> None:
Gather some data that would be useful for future debugging.

2025-01-07 19:10 UTC, holmanb commented on cloudinit/config/cc_package_update_upgrade_install.py
> +            LOG.info(
This is expected, so the warnings log level doesn't make sense.

2025-01-08 14:49 UTC, TheRealFalcon commented on tests/integration_tests/modules/test_power_state_change.py
> +            ("halt", "+1", "0", re.escape("will execute: shutdown -H +1 msg")),
There's a good likelihood it never passed

2025-01-08 15:20 UTC, TheRealFalcon reviewed
General approach LGTM.

Can we get some unittests of the new context manager? We obviously need to mock the exit, but I think we could use the context manager and then just call the handler directly and check the logs.

Also, if we're concerned about all the places this would need to be plumbed, I'm wondering if it'd be possible to check the process tree and determine if whatever invoked the reboot was initiated by cloud-init and just ignore those. I'm not saying we should do that here, but it's an alternative to think about.

2025-01-08 15:20 UTC, TheRealFalcon commented on cloudinit/signal_handler.py
> +def default_handler(_num, _stack) -> None:
Unused?

2025-01-08 15:20 UTC, TheRealFalcon commented on cloudinit/signal_handler.py
> +        LOG.info("Signal state [%s] - custom handler.", sig)
I think this is actually the default case rather than SIG_DFL:
```
>>> def x(*args):
...     print('handler')
... 
>>> import signal
>>> y = signal.signal(signal.SIGINT, x)
>>> type(y)
<class 'builtin_function_or_method'>
>>> y()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyboardInterrupt
```

2025-01-08 19:33 UTC, TheRealFalcon commented on cloudinit/signal_handler.py
> +        if isinstance(sig, types.BuiltinFunctionType):
Shouldn't this be negated?

2025-01-08 21:09 UTC, holmanb commented
> determine if whatever invoked the reboot

Is that possible? Does systemd expose the PID/GID of the process that set a specific boot target? I can't think of a way to do this that wouldn't be completely broken.

2025-01-08 22:34 UTC, TheRealFalcon commented
> Is that possible?

[It appears so](https://stackoverflow.com/questions/4974140/get-pid-of-the-process-which-has-triggered-some-signal), but none of the options presented there seem reasonable for this use case, so...just ignore me :smile:

2025-01-08 22:40 UTC, holmanb commented
> > Is that possible?
> 
> [It appears so](https://stackoverflow.com/questions/4974140/get-pid-of-the-process-which-has-triggered-some-signal)

I still don't think so.


If a user passes a shutdown command through a script, cloud-init doesn't receive the signal from its own child process. The process that sends the signal on reboot/shutdown is systemd. What we would need for this to be possible is to know which process set the systemd boot target to shutdown / reboot / etc.

2025-01-09 15:18 UTC, TheRealFalcon approved these changes
LGTM!

Not something I'm asking to change, but I did find the new tests a bit hard to grok. Since the test body contains an `if` condition for each of the 2nd parametrizations, I think that 3 separate tests might have been more appropriate, but that could just be personal preference.

2025-01-09 15:20 UTC, TheRealFalcon commented
Hrm...my approval didn't see the CI failures yet. There appears to be some legitimate ones there, so let's not merge quite yet.

2025-01-10 15:57 UTC, TheRealFalcon requested changes
comments inline

2025-01-10 15:57 UTC, TheRealFalcon commented on cloudinit/signal_handler.py
> +    elif sig != signal.SIG_DFL:
```suggestion
    elif sig == signal.SIG_DFL:
```

I think this is the root of all of the current integration test failures on thsi branch.

2025-01-10 15:57 UTC, TheRealFalcon commented on cloudinit/signal_handler.py
> +def inspect_handler(sig: Union[int, Callable, None]) -> None:
Note that we won't actually see these logs unless we manually call cloud-init with `cloud-init --debug`. This is currently getting called pre-log setup.

2025-01-13 19:29 UTC, TheRealFalcon approved these changes
LGTM!

2025-01-13 19:39 UTC, merged