Holmanb/graceful integration test 2
canonical/cloud-init pull request #5926
Opened 2024-12-12 01:47 UTC by holmanb

## Proposed Commit Message

```
<type>(optional scope): <summary>  # no more than 72 characters

A description of what the change being made is and why it is being
made if the summary line is insufficient.  This should be wrapped at
72 characters.

If you need to write multiple paragraphs, feel free.

Fixes GH-NNNNN (GitHub Issue number. Remove line if irrelevant)
LP: #NNNNNN (Launchpad bug number. Remove line if irrelevant)
```

## Additional Context

## Test Steps

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

2025-01-06 19:58 UTC, TheRealFalcon commented on tests/integration_tests/reaper.py
> +class Reaper:
Based on the immediate instantiation afterwards I'm assuming this class is intended to be used as a singleton? If so, I think we should make the class name `_Reaper` so that it's more obvious.

But there's two instances. In conftest.py, you instantiate a new instance, but then in instances.py you reference the instance created in this file.

Also, the module docstring is out of date and I think function names like `reaper_start()` and `reaper_stop()` can be updated to just `start()` and `stop()` if they live inside the class.

2025-01-06 20:42 UTC, holmanb commented on tests/integration_tests/reaper.py
> +class Reaper:
> I'm assuming this class is intended to be used as a singleton

Yes

> But there's two instances.

Ahhhhhh, nice catch

2025-01-06 22:40 UTC, TheRealFalcon requested changes
This will be a nice improvement! I left a few inline comments, but nothing major.

2025-01-06 22:40 UTC, TheRealFalcon commented on tests/integration_tests/reaper.py
> +        for instance in self.undead_ledger:
This seems like an unlikely situation, but if we happen to get a buildup of undead instances, then we could hit a scenario where we finished testing right after we started this list and will sit waiting for a bunch of instances to die that will likely never die.

Think it's worth a `reaped_instances.empty()` check for every new item in the for loop?

2025-01-06 22:42 UTC, TheRealFalcon commented on tests/integration_tests/reaper.py
> +        if self.reaper_thread:
(suggestion (now deleted) from previous review was on the wrong line)
```suggestion
        if self.reaper_thread and reaper_thread.is_alive():
```

2025-01-06 22:47 UTC, TheRealFalcon commented on tests/integration_tests/reaper.py
> +                    "Reaper: the faults of incompetent abilities will be "
This shouldn't fit as well as it does :joy:

2025-01-06 23:20 UTC, holmanb commented on tests/integration_tests/reaper.py
> +        self.reaped_instances: Final[queue.Queue[IntegrationInstance]] = (
Why? This syntax should be valid 3.8.

FWIW mypy already reports errors on 3.8, so even if it didn't work on 3.8 this wouldn't be be anything new.
```
tests/unittests/cmd/devel/test_logs.py:145: error: Need type annotation for "tar_kwargs" (hint: "tar_kwargs: Dict[<type>, <type>] = ...")  [var-annotated]
tests/unittests/cmd/devel/test_logs.py:149: error: Unused "type: ignore" comment  [unused-ignore]
```

2025-01-06 23:22 UTC, holmanb commented on tests/integration_tests/reaper.py
> +                    "Reaper: the faults of incompetent abilities will be "
Heh :)

I was originally planning to remove the weird personification of this background thread, but it grew on me a little. If anyone objects I can remove it.

2025-01-06 23:31 UTC, holmanb commented on tests/integration_tests/reaper.py
> +        self.reaper_thread = threading.Thread(
> If that's a valid use case

I wasn't necessarily planning on it being a non-singleton, but I'm trying to make it robust (including in using it in ways that weren't originally intended) so I've added your suggestions. Thanks!

2025-01-06 23:37 UTC, holmanb commented on tests/integration_tests/reaper.py
> +        for instance in self.undead_ledger:
> scenario where we finished testing right after we started this list and will sit waiting for a bunch of instances to die that will likely never die.

Yeah, that could happen. Good point.

> Think it's worth a reaped_instances.empty() check for every new item in the for loop?

That alone wouldn't work, I suspect. A majority of the time when this code is running reaped_instances.empty() is probably true, since we removed all instanced from this queue just before running this code. But if `self.exit_reaper.is_set() and self.reaped_instances.empty()` then we can probably exit early to avoid the extra waiting.

2025-01-07 00:02 UTC, TheRealFalcon commented on tests/integration_tests/reaper.py
> +        self.reaped_instances: Final[queue.Queue[IntegrationInstance]] = (
```
Python 3.8.16 (default, Jul 22 2023, 21:38:13) 
[GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from queue import Queue
>>> x: Queue[str] = Queue()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'type' object is not subscriptable
>>> x: Queue = Queue()
>>> 
```

https://docs.python.org/3/whatsnew/3.9.html#type-hinting-generics-in-standard-collections

2025-01-07 00:05 UTC, TheRealFalcon commented on tests/integration_tests/reaper.py
> +                    "Reaper: the faults of incompetent abilities will be "
No objections from me!

2025-01-07 02:38 UTC, TheRealFalcon approved these changes
LGTM!

2025-01-07 05:01 UTC, holmanb commented
Thanks for the reviews @TheRealFalcon!

2025-01-07 05:06 UTC, merged