[enhancement]: Retry enhancement in OpenStack batch creation scenarios
canonical/cloud-init pull request #5943
Opened 2024-12-26 00:22 UTC by gglzf4

## Proposed Commit Message

```
<type>(optional scope): <summary>  # no more than 72 characters

A description of what the change being made is and why it is being
made if the summary line is insufficient.  This should be wrapped at
72 characters.

If you need to write multiple paragraphs, feel free.

Fixes GH-NNNNN (GitHub Issue number. Remove line if irrelevant)
LP: #NNNNNN (Launchpad bug number. Remove line if irrelevant)
```

## Additional Context

## Test Steps

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

2025-01-06 21:29 UTC, holmanb commented
Welcome @gglzf4! Please [sign the CLA](https://docs.cloud-init.io/en/latest/development/first_PR.html#sign-the-cla).

2025-01-07 07:56 UTC, gglzf4 commented
> Welcome @gglzf4! Please [sign the CLA](https://docs.cloud-init.io/en/latest/development/first_PR.html#sign-the-cla).

Thank you. I'll sign it right away.

2025-01-07 21:22 UTC, holmanb requested changes

2025-01-08 08:14 UTC, gglzf4 commented on cloudinit/sources/helpers/openstack.py
> +                if code == 404 or code < 400:
The HTTP status code >= 400 does not support retry is too general. Retry should be supported for the following HTTP status codes:
`408 Request Timeout`
`429 Too Many Requests`
`500 Internal Server Error`
`502 Bad Gateway`
`503 Service Unavailable`
`504 Gateway Timeout`

2025-01-10 08:38 UTC, gglzf4 commented
Please help review it

2025-01-10 08:40 UTC, gglzf4 commented
The HTTP status code >= 400 does not support retry is too general. Retry should be supported for the following HTTP status codes:
`408 Request Timeout`
`429 Too Many Requests`
`500 Internal Server Error`
`502 Bad Gateway`
`503 Service Unavailable`
`504 Gateway Timeout`

Please help review it! @holmanb @TheRealFalcon

2025-02-07 16:49 UTC, holmanb approved these changes
Thanks @gglzf4. This looks good to me!

2025-02-07 16:53 UTC, merged