Fix mounting of vfat on *BSD
canonical/cloud-init pull request #637
Opened 2020-10-29 12:11 UTC by igalic

## Proposed Commit Message
Fix mounting of vfat filesystems by normalizing the different names for vfat to "msdos" which works across BSDS.

## Additional Context

FreeBSD Bugzilla ref: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=250496
LP# https://bugs.launchpad.net/cloud-init/+bug/1901958

## Test Steps

This doesn't reproduce on Ubuntu.

## Checklist:
 - [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/hacking.html)
 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any documentation accordingly

2020-10-29 13:39 UTC, OddBloke commented on cloudinit/util.py
> +            if mtype in ["vfat", "msdosfs", "msdos"]:
We don't need `"msdos"` in this list; `mtypes[index]` is already `"msdos"` in that case.

```suggestion
            if mtype in ["vfat", "msdosfs"]:
```

2020-10-29 20:27 UTC, OddBloke requested changes
Thanks for this, @igalic! The way these tests are structured and the boundaries you have chosen to test along LGTM (as does the actual change itself!). I have some inline comments to clean up some details.

2020-10-29 20:27 UTC, OddBloke commented on cloudinit/tests/test_util.py
> +        m_subp.assert_called_with(
If we're using `assert_*` methods then we need `autospec=True` on the corresponding patch call; (search for "autospec" in https://cloudinit.readthedocs.io/en/latest/topics/hacking.html#testing).

2020-10-29 20:27 UTC, OddBloke commented on cloudinit/tests/test_util.py
> +        m_subp.assert_called_with(
Same here.

2020-10-29 20:27 UTC, OddBloke commented on cloudinit/tests/test_util.py
> +        m_is_BSD.return_value = "SomeBSD"
Should this just be `= True`?

2020-10-29 20:27 UTC, OddBloke commented on cloudinit/tests/test_util.py
> +    def test_normalize_vfat_on_bsd(self, m_tmpdir, m_subp, m_is_BSD):
This test could be expanded via parameterisation to also exercise the "msdosfs" codepath (and perhaps also combined with the below test). Let me know if you'd like more details and I can run you through it!

2020-10-29 20:37 UTC, igalic commented on cloudinit/tests/test_util.py
> +    @mock.patch("platform.system")
yeah, i thought i could get away with cheating ;)

2020-11-02 15:27 UTC, OddBloke approved these changes
LGTM, thanks!

2020-11-02 17:01 UTC, merged