Add example configuration for datasource `AliYun`
canonical/cloud-init pull request #751
Opened 2021-01-06 05:53 UTC by bittopaz

## Proposed Commit Message

```
Add example configuration for datasource `AliYun`
```

## Additional Context

## Test Steps

## Checklist:

 - [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/hacking.html)
 - [x] I have updated or added any unit tests accordingly
 - [x] I have updated or added any documentation accordingly

2021-01-06 22:08 UTC, OddBloke requested changes
Thanks for the submission, @bittopaz! I've left a few comments inline.

2021-01-06 22:08 UTC, OddBloke commented on doc/rtd/topics/datasources/aliyun.rst
> +configuration (in `/etc/cloud/cloud.cfg` or `/etc/cloud/cloud.cfg.d/`).
This is reStructuredText, not Markdown, so you need double ticks here:

```suggestion
configuration (in ``/etc/cloud/cloud.cfg`` or ``/etc/cloud/cloud.cfg.d/``).
```

2021-01-06 22:08 UTC, OddBloke commented on doc/rtd/topics/datasources/aliyun.rst
> +      metadata_urls: ["http://100.100.100.200", "http://instance-data:8773"]
This doesn't match the AliYun default: https://github.com/canonical/cloud-init/blob/e5c67478136e1942a981ee18785ceb26579d0041/cloudinit/sources/DataSourceAliYun.py#L13

2021-01-06 22:08 UTC, OddBloke commented on doc/rtd/topics/datasources/aliyun.rst
> +      max_wait: 300
These don't match the AliYun defaults (which are inherited from the EC2 datasource): https://github.com/canonical/cloud-init/blob/e5c67478136e1942a981ee18785ceb26579d0041/cloudinit/sources/DataSourceEc2.py#L69-L70

2021-01-07 10:36 UTC, bittopaz commented on doc/rtd/topics/datasources/aliyun.rst
> +      support_xen: false
Thanks for reviewing this PR. 
hmm, this is strange then, I got the example from their [doc](https://www.alibabacloud.com/help/doc-detail/57803.htm)
Looks like Alicloud maintains its own version of cloud-init inside.

Anyway, I'll remove this line.

2021-01-07 10:51 UTC, bittopaz commented
@OddBloke  Thanks for taking time reviewing the changes. I have updated accordingly and rebased the commits.

2021-01-07 14:53 UTC, OddBloke approved these changes
Thanks for the updates!

(As this is a doc change only, we do not require CLA signature, so this is good to land.)

2021-01-07 15:14 UTC, merged