archlinux: Use hostnamectl to set the transient hostname
canonical/cloud-init pull request #797
Opened 2021-01-30 23:51 UTC by klausenbusk

## Proposed Commit Message
```
archlinux: Use hostnamectl to set the transient hostname

hostname (inetutils) isn't installed per default on arch, so switch
to hostnamectl which is installed per default (systemd).
```

## Test Steps
This has been tested manually with the Arch Linux [cloud-init package](https://archlinux.org/packages/community/any/cloud-init/) (`arch.py` patched with the changes in this commit) and `inetutils` forcefully removed (`pacman -Rsddn inetutils`).

## Checklist:

 - [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/hacking.html)
 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any documentation accordingly

2021-01-30 23:54 UTC, klausenbusk commented
The CLA stuff is part of: https://github.com/canonical/cloud-init/pull/796

2021-02-02 20:50 UTC, TheRealFalcon requested changes
Your commit message lists the reason for making the change, but can you add a comment to the method to explain why you're overriding the default behavior? Also, can you add similar logging and try/except behavior that the base method has?

2021-02-03 03:06 UTC, klausenbusk commented
Fixed

2021-02-03 14:02 UTC, TheRealFalcon reviewed
I suggested one more change inline. Should be good to go after that. I'll wait for your other PR to merge given that the CLA change is in that one.

2021-02-03 14:02 UTC, TheRealFalcon commented on cloudinit/distros/arch.py
> +        try:
```suggestion
        LOG.debug("Non-persistently setting the system hostname to %s",
                  hostname)
        try:
```

2021-02-03 14:17 UTC, TheRealFalcon approved these changes
Thanks!

2021-02-08 15:04 UTC, TheRealFalcon commented
Hey @klausenbusk , the only thing this PR is waiting on is the CLA signers file, which is added in #796 . If you need to take your time on #796 , feel free to move that commit over to this PR and I can land this one as soon as possible. If you'd rather just wait until the other PR is finished, that is fine as well.

2021-02-25 16:12 UTC, merged

2021-02-25 16:13 UTC, TheRealFalcon commented
@klausenbusk , since this PR was close to getting auto-closed, and since you've already signed the CLA, I took the liberty of moving your addition to the github CLA signers file over to this PR and merging it. Thanks for the contribution!