tools/write-ssh-key-fingerprints: do not display empty header/footer
canonical/cloud-init pull request #817
Opened 2021-02-20 19:44 UTC by dermotbradley

When console output of SSH info is disabled show no headers/footers.

Prevent risk of message text being interpreted as "logger" option by
appending "--" to logger options.

Correct syslog output that was tagged with "ec2" regardless of DataSource
in use. Now use "cloud-init" tag instead.

Various "shellcheck" corrections.

Add testcase for disabled output of SSH host keys.

LP: #1915460

Provides alternative solution to #811.

## Test Steps

In user-data config add either, or both, of the following lines:

```
ssh_fp_console_blacklist: [ 'ssh-dsa', 'ssh-dss', 'ssh-rsa', 'ssh-ed25519' ]
ssh_key_console_blacklist: [ 'ssh-dsa', 'ssh-dss', 'ssh-rsa', 'ssh-ed25519' ]
```

## Checklist:

 - [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/hacking.html)
 - [x] I have updated or added any unit tests accordingly
 - [x] I have updated or added any documentation accordingly

2021-03-03 20:27 UTC, TheRealFalcon requested changes
Overall, this change looks good. Might be worth making a function out of the shellcheck comment  and the `logger` options to cleanup the calls to `logger`.

I appreciate the additional cloud tests, but unfortunately these tests are deprecated now. Docs for the new test framework are [here](https://cloudinit.readthedocs.io/en/latest/topics/integration_tests.html), but the TLDR for this PR would be to add a test to [test_keys_to_console.py](https://github.com/canonical/cloud-init/blob/master/tests/integration_tests/modules/test_keys_to_console.py) with a full blacklist in the cloud-config and assert there's no headers/footers (similar to the bottom two tests in the file)

2021-03-03 22:06 UTC, dermotbradley commented
Hi there

I'll find some time in the next few days to work on this.

Regarding the correction of the 'ec2' string - @OddBloke mentioned on IRC that there might be some stuff out there (Subquity?) relying on that value and he would look into it further. I can drop this portion of the PR if its likely to cause problems.

2021-03-19 00:51 UTC, dermotbradley commented
> Overall, this change looks good. Might be worth making a function out of the shellcheck comment and the `logger` options to cleanup the calls to `logger`.

Done.

> the TLDR for this PR would be to add a test to [test_keys_to_console.py](https://github.com/canonical/cloud-init/blob/master/tests/integration_tests/modules/test_keys_to_console.py) with a full blacklist in the cloud-config and assert there's no headers/footers (similar to the bottom two tests in the file)

Done.

2021-03-23 04:06 UTC, dermotbradley commented
@mitechie ping!

2021-03-23 11:00 UTC, mitechie commented
pong! I've cleared the tag and we'll get another round of reviews going. Thanks for the ping.

2021-03-23 22:37 UTC, TheRealFalcon requested changes
Looking good. Just a couple changes the integration test needed

2021-03-23 22:37 UTC, TheRealFalcon commented on tests/integration_tests/modules/test_keys_to_console.py
> +"""
```suggestion
BLACKLIST_ALL_KEYS_USER_DATA = """\
#cloud-config
ssh_fp_console_blacklist: [ssh-dsa, ssh-ecdsa, ssh-ed25519, ssh-rsa, ssh-dss, ecdsa-sha2-nistp256]
"""  # noqa: E501
```

2021-03-23 22:37 UTC, TheRealFalcon commented on tests/integration_tests/modules/test_keys_to_console.py
> +    @pytest.mark.parametrize("key_type", ["DSA", "ECDSA", "ED25519", "RSA"])
```suggestion
```

2021-03-25 03:14 UTC, dermotbradley commented on tests/integration_tests/modules/test_keys_to_console.py
> +    @pytest.mark.parametrize("key_type", ["DSA", "ECDSA", "ED25519", "RSA"])
Done

2021-03-25 03:14 UTC, dermotbradley commented on tests/integration_tests/modules/test_keys_to_console.py
> +"""
Done

2021-03-25 20:46 UTC, TheRealFalcon approved these changes
Thanks!

2021-03-25 21:18 UTC, merged