Retrieve username and hostname from IMDS
canonical/cloud-init pull request #865
Opened 2021-04-09 17:06 UTC by trstringer

## Proposed Commit Message

```
Retrieve username, hostname, and disable password from IMDS.

This change allows us to retrieve the username and hostname from
IMDS instead of having to rely on the mounted OVF.
```

## Test Steps

The following script (which relies on [az-cli-helpers (GitHub)](https://github.com/trstringer/az-cli-helpers) functions) tests and makes sure that the desired functionality is there:

```bash
#!/bin/bash -i

# Test first with able to mount the ISO.
NEW_RESOURCE_NAME=$(resource_name)
sleep 2
az_vm_cloud_init_install
echo "Completed with $NEW_RESOURCE_NAME"
CLOUD_INIT_LOG=$(az_vm_ssh $NEW_RESOURCE_NAME "cat /var/log/cloud-init.log")

# Validate log messages and lack of errors.
if ! echo "$CLOUD_INIT_LOG" | grep "Username retrieved from IMDS"; then
    echo "Failed getting username from IMDS"
    exit 1
else
    echo "Successfully retrieved username from IMDS"
fi
if ! echo "$CLOUD_INIT_LOG" | grep "Hostname retrieved from IMDS"; then
    echo "Failed getting hostname from IMDS"
    exit 1
else
    echo "Successfully retrieved hostname from IMDS"
fi
if ! echo "$CLOUD_INIT_LOG" | grep "Disable password retrieved from IMDS"; then
    echo "Failed getting disable password from IMDS"
    exit 1
else
    echo "Successfully retrieved disable password from IMDS"
fi

echo "Successfully validated with ISO"
unset NEW_RESOURCE_NAME

# Test without mounting the ISO
NEW_RESOURCE_NAME=$(resource_name)
sleep 2
az_vm_cloud_init_install ~/dev/other/disable_udf.sh
echo "Completed with $NEW_RESOURCE_NAME"
CLOUD_INIT_LOG=$(az_vm_ssh $NEW_RESOURCE_NAME "cat /var/log/cloud-init.log")

# Validate log messages and lack of errors.
if ! echo "$CLOUD_INIT_LOG" | grep "Username retrieved from IMDS"; then
    echo "Failed getting username from IMDS with no OVF"
    exit 1
else
    echo "Successfully retrieved username from IMDS with no OVF"
fi
if ! echo "$CLOUD_INIT_LOG" | grep "Hostname retrieved from IMDS"; then
    echo "Failed getting hostname from IMDS with no OVF"
    exit 1
else
    echo "Successfully retrieved hostname from IMDS with no OVF"
fi
if ! echo "$CLOUD_INIT_LOG" | grep "Disable password retrieved from IMDS"; then
    echo "Failed getting disable password from IMDS with no OVF"
    exit 1
else
    echo "Successfully retrieved disable password from IMDS with no OVF"
fi

echo "Validation completed successfully"
```

## Checklist:

 - [ ] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/hacking.html)
 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any documentation accordingly

2021-04-12 14:48 UTC, anhvoms commented on cloudinit/sources/DataSourceAzure.py
>                      '%s was not mountable' % cdev, logger_func=LOG.warning)
probably should downgrade this from a WARNING to a DEBUG

2021-04-23 17:07 UTC, TheRealFalcon requested changes
Overall this looks good. I agree with Anh's comment about the log message, and then also this branch needs a rebase and resolving of the merge conflict.

2021-04-23 17:07 UTC, TheRealFalcon commented on cloudinit/sources/DataSourceAzure.py
> +                log_msg = 'Keys not in OpenSSH format, using OVF'
nit: might be worth having a default log message before the try block just in case there's a different exception raised that is uncaught.

2021-04-23 17:07 UTC, TheRealFalcon commented on cloudinit/sources/DataSourceAzure.py
> +                log_msg = 'Retrieved {} keys from OVF'.format(len(ssh_keys))
same nit for this log message too

2021-04-23 23:02 UTC, trstringer commented
@TheRealFalcon, thanks for the review! I've made yours and @anhvoms's changes!

2021-04-26 13:40 UTC, TheRealFalcon approved these changes

2021-04-26 13:41 UTC, merged

2021-05-04 14:20 UTC, TheRealFalcon commented
In doing some testing for release, I noticed that the changes here caused https://github.com/canonical/cloud-init/blob/master/tests/integration_tests/bugs/test_lp1910835.py to fail. I realize that this issue might be fixed on the Azure side now, but we'd feel more comfortable still having a check for and a rejection of keys with containing CRLF. Just as an FYI, I plan on putting together a change to address this.