add DragonFlyBSD support
canonical/cloud-init pull request #904
Opened 2021-05-17 00:45 UTC by goneri

- Mostly based on FreeBSD, the main exception is that
  `find_devs_with_on_freebsd` does not work.
- Since we cannot get the CDROM or the partition labels,
  `find_devs_with_on_dragonflybsd()` has a more naive approach and
  returns all the block devices.

2021-05-17 01:20 UTC, goneri commented
Note: you can try the DragonFly BSD 6.0.0 image from https://bsd-cloud-image.org/

2021-05-21 16:59 UTC, TheRealFalcon requested changes
Hey @goneri , thanks for this addition. Overall, this looks very good. I left some comments inline along with some comments for additions and testing here.

Should we add dragonfly here?
https://github.com/canonical/cloud-init/blob/master/cloudinit/distros/__init__.py#L47
and here?
https://github.com/canonical/cloud-init/blob/master/tools/render-cloudcfg#L7

Additionally, we would like some unit testing to go along with this addition.

Can we get unit testing to make sure it is detected correctly? Similar to:
https://github.com/canonical/cloud-init/blob/master/cloudinit/tests/test_util.py#L464

Along with testing for the new `find_devs` implementation? Simlar to:
https://github.com/canonical/cloud-init/blob/master/tests/unittests/test_util.py#L890
or perhaps:
https://github.com/canonical/cloud-init/blob/master/tests/unittests/test_datasource/test_nocloud.py#L292

2021-05-21 16:59 UTC, TheRealFalcon commented on cloudinit/distros/freebsd.py
> +    def _select_hostname(self, hostname, fqdn):
With the `prefer_fqdn` class attribute, we no longer need to override this method.

2021-05-21 16:59 UTC, TheRealFalcon commented on cloudinit/distros/freebsd.py
> +class FreeBSD(cloudinit.distros.bsd.BSD):
I realize `bsd.py` doesn't follow the trend of the class being named `Distro`, but can we leave that as the one exception and let this be named `Distro` here as well?

2021-05-21 16:59 UTC, TheRealFalcon commented on cloudinit/distros/freebsd.py
> +class Distro(FreeBSD):
If we leave the other class named `Distro`, this I believe we can remove this class.

2021-05-21 16:59 UTC, TheRealFalcon commented on config/cloud.cfg.tmpl
> +{% if variant not in ["netbsd", "openbsd", "dragonfly"] %}
Nit: Can we put "dragonfly" at the front of this list to keep it alphabetical?

2021-05-21 16:59 UTC, TheRealFalcon commented on config/cloud.cfg.tmpl
> +{% if variant not in ["freebsd", "netbsd", "openbsd", "dragonfly"] %}
Same comment about alphabetical here

2021-05-21 16:59 UTC, TheRealFalcon commented on cloudinit/distros/dragonflybsd.py
> +class Distro(cloudinit.distros.freebsd.FreeBSD):
If we follow my other comment, the base should be `cloudinit.distros.freebsd.Distro` then

2021-06-02 16:46 UTC, TheRealFalcon reviewed
Thanks for addressing my inline comments. Did you see my overall comments on the review though? It looks like they still need to be addressed. We still need a couple unit tests, and there might be a place or two you would want to add the distro.

Previous comment:
```
Should we add dragonfly here?
https://github.com/canonical/cloud-init/blob/master/cloudinit/distros/__init__.py#L47
and here?
https://github.com/canonical/cloud-init/blob/master/tools/render-cloudcfg#L7

Additionally, we would like some unit testing to go along with this addition.

Can we get unit testing to make sure it is detected correctly? Similar to:
https://github.com/canonical/cloud-init/blob/master/cloudinit/tests/test_util.py#L464

Along with testing for the new find_devs implementation? Simlar to:
https://github.com/canonical/cloud-init/blob/master/tests/unittests/test_util.py#L890
or perhaps:
https://github.com/canonical/cloud-init/blob/master/tests/unittests/test_datasource/test_nocloud.py#L292
```

2021-06-02 16:58 UTC, goneri commented
Oh indeed, I totally missed the comment. I will work on that. Thank you for the review!

2021-06-05 23:17 UTC, goneri commented
> Should we add dragonfly here?
> https://github.com/canonical/cloud-init/blob/master/cloudinit/distros/__init__.py#L47

I see I also need to add OpenBSD and NetBSD. Can I do that in another iteration?

> and here?
> https://github.com/canonical/cloud-init/blob/master/tools/render-cloudcfg#L7

I use `freebsd` variant for now and `tools/build-on-freebsd` works fine.

I'm working on the unit-tests.

2021-06-07 13:57 UTC, TheRealFalcon commented
Hey @goneri , I noticed some new commits. Are you looking for a re-review yet?

2021-06-07 17:38 UTC, goneri commented
I've yet to add a test in test_nocloud.py. But yes, an early feedback is welcome.

2021-06-13 20:29 UTC, goneri commented
Regarding nocloud, I don't think we need any special unittest since 72f6eb0339f7fcf7b8b02be2e86e5f7477cf731c. They current code base relies on `cloudinit.util` which is tested.

2021-06-14 19:37 UTC, TheRealFalcon approved these changes

2021-06-14 19:39 UTC, merged

2021-06-14 20:41 UTC, goneri commented
Thank you @TheRealFalcon!