Add Rocky Linux support to cloud-init
canonical/cloud-init pull request #906
Opened 2021-05-19 03:15 UTC by nazunalika

## Proposed Commit Message

```
summary: Add support for Rocky Linux

Rocky Linux is a RHEL-compatible distribution so all changes that have
been made should be trivial.
```

## Additional Context
https://rockylinux.org

We currently have RC1 out (for version 8.3) and currently working on 8.4. We
had to redo our patches for 8.4 as it was rebased. We realized an upstream PR
was not made for our distribution, hence this submission.

Please let me know if I made a mistake anywhere throughout this PR and I
will try to correct it.

Thank you!

## Test Steps

## Checklist:

 - [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/hacking.html)
 - [x] I have updated or added any unit tests accordingly
 - [x] I have updated or added any documentation accordingly

2021-05-24 19:18 UTC, TheRealFalcon requested changes
Thanks for this submission. Overall this looks good. A few notes...

Most of the lists you added `rocky` to were in alphabetical order. Instead of adding rocky to the end of the list, can you add it to keep the ordering alphabetical?

One of the unit tests you wrote is failing on CI. It's because of the parsing of `/etc/redhat-release` is expecting a codename after the version number. Would it be possible to update [the implementation](https://github.com/canonical/cloud-init/blob/master/cloudinit/util.py#L432) to make the codename optional?

I suggested a change inline for the other failing unit test.

2021-05-25 01:43 UTC, nazunalika commented
I believe I addressed the alphabetical order lists and also the code name. We added a code name recently but I didn't provide an updated set of info. Hopefully that addressed that issue there. I couldn't find your suggestion in the modified file list. Or perhaps I've looked in the wrong place.

2021-05-25 02:05 UTC, TheRealFalcon reviewed
Hmmm, weird...must have put that suggestion in a different tab then I closed or something. Should be here now.

2021-05-25 02:05 UTC, TheRealFalcon commented on tests/unittests/test_cli.py
> +             'fedora, rocky'),
This is checking that the list in cc_ntp.py matches some documentation output. Unfrotunately it hasn't been updated in a while, but this should fix it.
```suggestion
            ('**Supported distros:** almalinux, alpine, centos, debian, '
             'fedora, opensuse, rhel, rocky, sles, ubuntu'),
```

2021-05-25 13:24 UTC, TheRealFalcon approved these changes
Looks good now, thanks!

2021-05-25 13:25 UTC, merged