openbsd/net: flush the route table on net restart
canonical/cloud-init pull request #908
Opened 2021-05-22 04:16 UTC by goneri

Ensure we've got a clean environment before we restart the network.

In some cases, the `sh /etc/netstart` is not enough to restart the
network. A previous default route remains in the route table and
as a result the network is broken.
Also `sh /netstart` does not kill `dhclient`.
The problen happens for instance with OVH OpenStack SBG3.

2021-05-24 19:24 UTC, TheRealFalcon requested changes
Looks good, but we need to fix the flake8 errors.

2021-05-24 19:24 UTC, TheRealFalcon commented on cloudinit/net/openbsd.py
> +        subp.subp(['route', 'flush', 'default'], capture=True, rcs=[0 ,1])
```suggestion
        subp.subp(['pkill', 'dhclient'], capture=True, rcs=[0, 1])
        subp.subp(['route', 'del', 'default'], capture=True, rcs=[0, 1])
        subp.subp(['route', 'flush', 'default'], capture=True, rcs=[0, 1])
```

2021-05-25 19:47 UTC, TheRealFalcon approved these changes

2021-05-25 19:48 UTC, merged

2021-05-25 20:09 UTC, goneri commented
Thank you @TheRealFalcon.